### ISSUE TITLE
gnutls_handshake() failed when do apt-get update

### ISSUE THREAD

**Issue by yywudi** [shadowsocks/shadowsocks-org#10]
VPS: KVM with Ubuntu 14.04 installed.

cat /etc/issue
Ubuntu 14.04.3 LTS \n \l

Add below to /etc/apt/sources.list
deb http://shadowsocks.org/ubuntu trusty main

then do apt-get update
apt-get reply as:

Err http://shadowsocks.org trusty/main amd64 Packages
Err http://shadowsocks.org trusty/main i386 Packages
Ign http://shadowsocks.org trusty/main Translation-en_US
Ign http://shadowsocks.org trusty/main Translation-en
Err http://shadowsocks.org trusty/main amd64 Packages
  gnutls_handshake() failed: Handshake failed
Err http://shadowsocks.org trusty/main i386 Packages
  gnutls_handshake() failed: Handshake failed
W: Failed to fetch http://shadowsocks.org/ubuntu/dists/trusty/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed

W: Failed to fetch http://shadowsocks.org/ubuntu/dists/trusty/main/binary-i386/Packages  gnutls_handshake() failed: Handshake failed

E: Some index files failed to download. They have been ignored, or old ones used instead.

anything wrong in the website? or anything wrong in my env?

**Comment by madeye** [comment]
Try again later.
