### ISSUE TITLE
Padding shouldn't be used in SIP002 URI Scheme

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-org#100]
Correct examples should be:

* `ss://YWVzLTEyOC1nY206dGVzdA@192.168.100.1:8888#Example1`
* `ss://cmM0LW1kNTpwYXNzd2Q@192.168.100.1:8888/?plugin=obfs-local%3Bobfs%3Dhttp#Example2`

**Comment by database64128** [comment]
Also fixed in c87830c. Looks like the CI needs to be manually triggered. @madeye
