### ISSUE TITLE
What is the sssniff?

### ISSUE THREAD

**Issue by codeltu-gorace** [shadowsocks/shadowsocks-org#101]
https://github.com/madeye/sssniff

In readme I can see ss(r)Sniff and sssniff. So, that is the ShadowSocksR? Is it a modification of Shadowsocks?
"Finally, browse the web via your SS proxy. When the script detects more than 15 suspicious connections to/from one source, it will flag it to be a ShadowSocks server and print to the terminal." - but computer generate a lot of traffic. How does it relate with ShadowSocks. And what means suspicious?
"ShadowSocks is famous for its randomness feature" - is it about randomly generated IV?
"however, the first packet of a connection is usually not expected to be random. Even in a TLS session, we expect to see some plaintext sections in the handshake stage." - but SS encrypt data by long key and randomply generated IV, so data from client to SS will be totally encrypted, without plain text.
"Therefore, one can detect ShadowSocks traffic by simply looking at the first few packets and calculating their entropy (as a measure of randomness). Together with some minor adjustments, this method suffices to detect the current ShadowSocks protocol at a high accuracy." - that do you mean? If you will look at first packets you will see encrypted data. Moreover you can't know, that cipher type is used, so it is imposible to cut encrypted data from IV. So how can you calculate entropy, if every connection encrypted by random IV?
So I can`t understand, where sssniff must work - on ISP, client or server side? How it will calculate entropy of randomly encrypted data? What difference between SSR and SS?

**Comment by lcdtyph** [comment]
SSR used to be a fork of origin SS, and came up with the obfuscation at an earlier time.

A connection is identified by a five-tuple, and in most situation, the server port is always the same. So you can just filter the traffic to the same destination and do the mathematics.

Not just randomly generated IV. Actually IV, or nonce, is totally not randomly generated when you use an aead cipher. I think randomness feature here means weak feature.

> but SS encrypt data by long key and randomply generated IV, so data from client to SS will be totally encrypted, without plain text.

So that can be a feature to detect ss traffic, right? The unknown traffic is always suspicious. 

>that do you mean? If you will look at first packets you will see encrypted data. Moreover you can't know, that cipher type is used, so it is imposible to cut encrypted data from IV. So how can you calculate entropy, if every connection encrypted by random IV?

According to the information theory, more randomness data has a higher entropy. Here randomness means that all variables will occur with nearly the same probability. Also, information entropy is well-defined with a formulae.

**Comment by wongsyrone** [comment]
> totally not randomly generated

It depends on your RNG. I did my best to use modern one, but who knows whether some clever users or developers change the code.

**Comment by lcdtyph** [comment]
@wongsyrone I mean while using an **aead cipher**, nonce is counting from all-zero bytes, instead of randomly generated.

**Comment by wongsyrone** [comment]
NONCE is the number used only ONCE. It doesn't require to be random.

**Comment by lcdtyph** [comment]
I thought that nonce was the same thing as IV. One is usually used in stream cipher context, the other is used in aead cipher context.

**Comment by wongsyrone** [comment]
https://crypto.stackexchange.com/questions/8495/what-are-the-requirements-of-a-nonce

The requirements depend on the protocol being designed. We already have salt and HKDF in AEAD protocol to ensure randomness; it doesn't require nonce to be random as well.

**Comment by lcdtyph** [comment]
Thanks for the correction 😆 !

**Comment by wongsyrone** [comment]
Even if the nonce requires to be random as well, don't panic, since Shadowsocks is not designed to secure the traffic.

**Comment by lcdtyph** [comment]
Year, I just wanted to tell OP that IV and nonce are not always randomly generated~~
