### ISSUE TITLE
Will Shadowsocks support AES-256-CBC cipher?

### ISSUE THREAD

**Issue by ProgrammingLife** [shadowsocks/shadowsocks-org#105]
AES-256-CFB is good for text data encryption but not for binary files enc. Will Shadowsocks support AES-256-CBC cipher?

**Comment by shinku721** [comment]
AEAD ciphers (AES-GCM, chacha20-ietf-poly1305, ...) are recommended.
Why do you want the CBC mode?

**Comment by Mygod** [comment]
> AES-256-CFB is good for text data encryption but not for binary files enc.

Citation needed.
