### ISSUE TITLE
Link to repo of shadowsocks-go is wrong.

### ISSUE THREAD

**Issue by xhorn-pan** [shadowsocks/shadowsocks-org#106]
when you navigate from index page ->"spec"-> "implementations"->"Servers"->"shadowsocks-go", it links to [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev). I think it should be [shadowsocks-go](https://github.com/shadowsocks/shadowsocks-go)

**Comment by leesah** [comment]
The html files are built from markdown source code. Changes like this will be lost after rebuild of site.

**Comment by xhorn-pan** [comment]
It is fixed, thanks.
