### ISSUE TITLE
Can't run grunt

### ISSUE THREAD

**Issue by librehat** [shadowsocks/shadowsocks-org#11]
Freshly installed Fedora 23.

Get this error message. And it doesn't make any differences with --force
```bash
Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module 'source-map'
Loading "less.js" tasks...ERROR
>> Error: Cannot find module 'lodash'
Loading "connect.js" tasks...ERROR
>> Error: Cannot find module 'connect'
Warning: Task "less:docs" not found. Use --force to continue.
```

**Comment by madeye** [comment]
```
npm install -g grunt-cli
npm install
grunt
```

**Comment by madeye** [comment]
Have you already run `npm install`?

**Comment by librehat** [comment]
Yes I did. It didn't help

**Comment by meowlab** [comment]
Try remove `node_modules` directory and do `npm install` again, or re-clone the repo may help

**Comment by librehat** [comment]
@meowlab Removing `node_modules` and re-run `npm install` solved this. Thanks
