### ISSUE TITLE
Automated build & deployment of site

### ISSUE THREAD

**Issue by leesah** [shadowsocks/shadowsocks-org#110]
I'd like to propose automating the building and deploying of the site by employing [`grunt-gh-pages`](/tschaub/grunt-gh-pages).

### Proposed setup

The changes are as follows:
 * A `master` branch is created from the latest commit on `gh-pages` branch.
 * `en/` is removed on `master` branch.
 * The purpose of `master` branch is to trace the changes in:
   * The markdown source files, `/src/*`.
   * The static assets and configuration files, etc.
 * The `gh-pages` branch will then only contain files for the site deployment, i.e. the final outputs.
 * A job on Travis is triggered by every push on `master` branch, builds the site, and push the outputs to `gh-pages` branch.

### Expected benefits

These changes are supposed to bring the following benefits:
 * It'll be obvious for contributors that they should update the markdown source files instead of the html files, because apparently they won't find any html files to update on `master`.
 * Contributors won't have to setup a local NodeJS environment.
 * Pull request are automatically verified.
 * Final output is cleaner.

### Preview

Files kept on `master` branch: (_note the missing `en/` directory_)
```bash
shadowsocks-org (master)$ tree -L 2 -a -I .git
.
├── assets
│   ├── css
│   ├── fonts
│   ├── img
│   └── js
├── CNAME
├── .gitignore
├── .gitmodules
├── googlece4e3889b18bc841.html
├── Gruntfile.coffee
├── index.html
├── LICENSE
├── package.json
├── README.md
├── src
│   ├── content
│   ├── jade
│   ├── js
│   └── less
├── tasks
│   └── static.js
└── .travis.yml
```

Files that will appear on `gh-pages` branch: (_note the existence of `en/` directory and the absence of `src/`, `README.md`, `.gitignore`, etc._)
```bash
shadowsocks-org (gh-pages)$ tree -L 2 -a -I .git
.
├── assets
│   ├── css
│   ├── fonts
│   ├── img
│   └── js
├── CNAME
├── en
│   ├── about
│   ├── config
│   ├── download
│   ├── index.html
│   ├── sitemap.xml
│   └── spec
├── googlece4e3889b18bc841.html
└── index.html
```

**Comment by leesah** [comment]
I'm seeing a 404 error. Is GitHub set to use `gh-pages` branch for GitHub page?

**Comment by madeye** [comment]
It looks the previous build failed to generate content in `en/`. I triggered the build again and it works now.

**Comment by leesah** [comment]
Great.
