### ISSUE TITLE
Track-able content need to be removed

### ISSUE THREAD

**Issue by kimw** [shadowsocks/shadowsocks-org#113]
In page, https://shadowsocks.org/en/config/advanced.html, there's a trackable image exists. Please remove it.

The track able url,
- `http://ww4.sinaimg.cn/large/61b416b1gw1e9jmyps9vpj20dt0b4wg7.jpg`

**Comment by celeron533** [comment]
@kimw , could you please send a pull request?

**Comment by kimw** [comment]
@celeron533 sure, later.
