### ISSUE TITLE
Make Outline clients available in the downloads page

### ISSUE THREAD

**Issue by alalamav** [shadowsocks/shadowsocks-org#116]
The [Outline Clients](https://github.com/Jigsaw-Code/outline-client) are a cross-platform VPN or proxy client for [Windows](https://raw.githubusercontent.com/Jigsaw-Code/outline-releases/master/client/Outline-Client.exe), [macOS](https://itunes.apple.com/us/app/outline-app/id1356178125), [iOS](https://itunes.apple.com/us/app/outline-app/id1356177741), [Android](https://play.google.com/store/apps/details?id=org.outline.android.client), and [Chrome OS](https://github.com/Jigsaw-Code/outline-releases/blob/master/client/Outline.apk?raw=true). They are designed for use with the Outline Server software, but they are fully compatible with any Shadowsocks server that has UDP support enabled.

The Outline team would like to include its clients in the downloads page of shadowsocks.org. If the community finds value in this, we would be happy to submit a pull request.

**Comment by madeye** [comment]
Yes, please submit a pull request.

**Comment by wongsyrone** [comment]
I would like to see the Outline people contribute code to Shadowsocks.

**Comment by Mygod** [comment]
> I would like to see the Outline people contribute code to Shadowsocks.

I would like to see anybody contribute code to Shadowsocks.
