### ISSUE TITLE
Python script that parses config file and generates a client configuration URI

### ISSUE THREAD

**Issue by amayatsky** [shadowsocks/shadowsocks-org#121]
Not an issue but an improvement of sorts.

Got tired of manually creating the config URI using the web form here: https://www.shadowsocks.org/en/config/quick-guide.html

So we've created a simple python script to do that in a terminal:
https://github.com/amayatsky/shadowsocks-url-generator

All you need to do is run a single command and get an URI in return :)

Is there any chance this has some value to the community and maybe could be included in a setup guide or docs?

Thanks!

**Comment by YukariHinata** [comment]
Hi, the URI scheme in the page you refer to is the old one, the new URI scheme can be found here:  
https://www.shadowsocks.org/en/spec/SIP002-URI-Scheme.html

Most of the client apps including 'Outline' already support this new scheme :)

And here is a simple script I'm using (requires python 3):  
https://gist.github.com/YukariHinata/652990642d0483c861a52005e34404bf
