### ISSUE TITLE
Transport plugin with websocket

### ISSUE THREAD

**Issue by madeye** [shadowsocks/shadowsocks-org#139]
I tried https://github.com/erebe/wstunnel as a transport plugin recently. By tunneling shadowsocks traffic on websocket and accelerated by CDN, the performance looks quite good.

If anyone interested, a new plugin (written in golang is preferred) with websocket (https://github.com/gorilla/websocket) is welcome.

**Comment by VictoriaRaymond** [comment]
Why don't you guys even take a look at V2Ray?

**Comment by madeye** [comment]
@VictoriaRaymond Yeah, I knew V2Ray can do this. But it makes no sense to use V2Ray as a plugin of shadowsocks. 😸

**Comment by VictoriaRaymond** [comment]
It is possible to run V2Ray in transport mode (i.e., without proxy protocol involved) as a plugin. It can tunnel for example socks <-> websocket, and can do connection reuse as suggested. I am not aware of any other existing software that provides similar functionalities.

**Comment by madeye** [comment]
Okay, it may be not a bad idea to employ v2ray as a transport plugin.

@VictoriaRaymond Any config example for "TCP over websocket" relay?

**Comment by madeye** [comment]
Cool!

Just follow @VictoriaRaymond's config and build a SIP003 plugin here: https://github.com/madeye/v2ray-plugin

**Comment by madeye** [comment]
It looks weird that I saw too many open files error, though I enabled mux in the config file and verified mux works with tcpdump.

```
2019/01/10 01:17:04 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
```

@VictoriaRaymond Any idea?

**Comment by madeye** [comment]
@VictoriaRaymond It looks v2ray cannot close spider or port scanner's HTTP connections correctly.

```
~#ss -lp -t -a | grep v2ray | wc -l
255

~# ss -lp -t -a | grep v2ray | head -n 20
ESTAB         0           0                              127.0.0.1:35672                          127.0.0.1:44045   users:(("v2ray-plugin",pid=11210,fd=235))
ESTAB         0           0                              127.0.0.1:35640                          127.0.0.1:44045   users:(("v2ray-plugin",pid=11210,fd=230))
ESTAB         0           0                              127.0.0.1:35660                          127.0.0.1:44045   users:(("v2ray-plugin",pid=11210,fd=248))
ESTAB         0           0                              127.0.0.1:34664                          127.0.0.1:44045   users:(("v2ray-plugin",pid=11210,fd=222))
ESTAB         0           0                              127.0.0.1:32822                          127.0.0.1:44045   users:(("v2ray-plugin",pid=11210,fd=135))
ESTAB         0           0                              127.0.0.1:35644                          127.0.0.1:44045   users:(("v2ray-plugin",pid=11210,fd=241))
ESTAB         0           0                              127.0.0.1:34576                          127.0.0.1:44045   users:(("v2ray-plugin",pid=11210,fd=209))
ESTAB         0           0                              127.0.0.1:35676                          127.0.0.1:44045   users:(("v2ray-plugin",pid=11210,fd=14))
ESTAB         0           0                              127.0.0.1:35680                          127.0.0.1:44045   users:(("v2ray-plugin",pid=11210,fd=224))
LISTEN        0           4096                                   *:http                                   *:*       users:(("v2ray-plugin",pid=11210,fd=3))
ESTAB         0           0                 [::ffff:139.x.x.x]:http             [::ffff:203.78.117.119]:32984   users:(("v2ray-plugin",pid=11210,fd=162))
ESTAB         0           0                 [::ffff:139.x.x.x]:http                [::ffff:37.98.34.79]:55386   users:(("v2ray-plugin",pid=11210,fd=38))
ESTAB         0           0                 [::ffff:139.x.x.x]:http              [::ffff:5.208.229.112]:53698   users:(("v2ray-plugin",pid=11210,fd=264))
ESTAB         0           0                 [::ffff:139.x.x.x]:http             [::ffff:91.133.205.152]:24163   users:(("v2ray-plugin",pid=11210,fd=140))
ESTAB         0           0                 [::ffff:139.x.x.x]:http              [::ffff:5.114.175.252]:18932   users:(("v2ray-plugin",pid=11210,fd=216))
ESTAB         0           0                 [::ffff:139.x.x.x]:http                [::ffff:46.51.88.96]:39544   users:(("v2ray-plugin",pid=11210,fd=211))
ESTAB         0           0                 [::ffff:139.x.x.x]:http            [::ffff:151.235.110.172]:50025   users:(("v2ray-plugin",pid=11210,fd=127))
ESTAB         0           0                 [::ffff:139.x.x.x]:http                [::ffff:5.124.133.9]:48279   users:(("v2ray-plugin",pid=11210,fd=115))
ESTAB         0           0                 [::ffff:139.x.x.x]:http             [::ffff:39.128.207.177]:17342   users:(("v2ray-plugin",pid=11210,fd=13))
ESTAB         0           0                 [::ffff:139.x.x.x]:http            [::ffff:188.159.242.112]:1523    users:(("v2ray-plugin",pid=11210,fd=160))
```

**Comment by VictoriaRaymond** [comment]
There are several timeout settings in your scenarion:

1. Insufficient HTTP header: infinite https://github.com/golang/go/issues/24138
1. Complete HTTP header, but not WebSocket: connections will be closed immediately
1. Complete WebSocket header: [8 sec](https://github.com/v2ray/v2ray-core/blob/master/transport/internet/websocket/hub.go#L28) until handshake is done
1. Full WebSocket handshake: [300 seconds (connIdle)](https://github.com/v2ray/v2ray-core/blob/master/features/policy/policy.go#L117) in dokodemo-door, as it doesn't have handshake phase.
1. After upstream server closes connection: [1 second](https://github.com/v2ray/v2ray-core/blob/master/features/policy/policy.go#L118)

I guess you are hitting either case 1 or 4. I will fix case 1 soon.

**Comment by madeye** [comment]
Yeah, it looks related to case 1. Looking forward to the fix.

**Comment by VictoriaRaymond** [comment]
Case 1 is fixed in https://github.com/v2ray/v2ray-core/commit/6146366a4ac2fabe7ca81f4c80ca48cbfb8e1f7a

**Comment by Mygod** [comment]
So I guess we are officially collaborating with @v2ray now? Very cool. 🤣 I'm very excited to give the new plugin a spin, especially QUIC and TLS. I will probably do it a few days later when I get the time to do so.

Reading the docs, I'm confused by the obfuscation type in QUIC transport. Isn't QUIC transport supposed to mimic the traffic of QUIC? How does it mimic other types of traffic at the same time? Also why is there a `key` field in `QuicObject`? Isn't Diffie-Hellman (or similar key exchange protocol) used to generate a fresh key for every connection for forward security?

**Comment by VictoriaRaymond** [comment]
1. Obfuscation is mainly for QoS. It is possible an ISP treats one kind of UDP traffic nicer than another.
2. The extra encryption is to prevent Quic traffic being sniff'ed. The SNI attack in TLS 1.2 is still possible. Until the standard is finalized and SNI is protected by Quic protocol, this is an easy way to deal with SNI attack.

Both settings are optional btw. You may use pure Quic by leaving both settings unset.

**Comment by Mygod** [comment]
1. Yes but I'm more concerned about how are those obfuscations implemented?
2. That makes sense. So how are the TLS certificates generated (or what hostname will v2ray use)? I don't think SNI (even in plaintext) is too big an issue as long as it's consistent (say using IP address directly or a valid hostname that will be correctly resolved).

**Comment by Mygod** [comment]
1. In that case, it seems like for security reasons, you should never use obfuscation alone (without encryption) since that can easily be classified as QUIC traffic trying to be something else (and therefore probably v2ray). But I guess it can still be useful.
2. So is hostname configurable or is it hardwired to `quic.internal.v2ray.com` for auto generation? (is this documented anywhere? sorry, I'm not really familiar with v2ray) I think user-configurable hostname for certificate generation would be a good addition.

**Comment by VictoriaRaymond** [comment]
1. It depends on how secure you wanna go, and how deep your ISP can inspect.
1. For auto generation, it is hardcoded. To use customized settings, you have two options:
    1. Generate a leaf certificate by yourself, where you can customize not only domain name, but other settings too
    1. Provide a [CA certificate](https://v2ray.com/chapter_02/05_transport.html#certificateobject) with `usage=issue`. Then V2Ray will auto-issue new certificate from the CA cert.

**Comment by Mygod** [comment]
Alright, sorry about having been off-topic. I hided the off-topic comments (this is a great feature) and moved the discussions (my points at least) to v2ray/discussion. Anyway, I'll check this v2ray-plugin sometime. Good work, everyone. 😅

**Comment by madeye** [comment]
Just add a new Android plugin here: https://github.com/madeye/v2ray-plugin-android

**Comment by madeye** [comment]
I think we can close this now.

**Comment by Mygod** [comment]
Can we also deprecate simple-obfs (meaning add a notice and archive simple-obfs and simple-obfs-android) as well? That code is quite an eyesore. For anyone that's interested, `failover` can be implemented at HTTP server side using something like [proxy](https://caddyserver.com/docs/proxy).

**Comment by madeye** [comment]
Yes, we should deprecate simple-obfs.

Maybe v2ray already do failover with some configs.

**Comment by Mygod** [comment]
Hmmm, [I don't think so](https://www.v2ray.com/en/configuration/transport/websocket.html).

**Comment by VictoriaRaymond** [comment]
Don't know what `failover` is. Assuming the plugin would tunnel traffic to another endpoint, if it is not a valid ss traffic.

V2Ray doesn't have such functionality. Instead, V2Ray relies on a Web server (caddy for example, as mentioned by @Mygod ) to filter out invalid requests.

There is a [feature request](https://github.com/v2ray/v2ray-core/issues/1393) for this.

**Comment by madeye** [comment]
Given the typical usage of this plugin is with a CDN, the `failover` feature is not a must-have here.

Just enable the CDN's URL overwrite feature and routing default path to some "common" website.

**Comment by Mygod** [comment]
Well just in case my point wasn't clear, I meant to say there is no need to include `failover` feature in v2ray-plugin. :sweat_smile:

**Comment by Mygod** [comment]
Here's a basic example of setting it up behind caddy just in case. v2ray-plugin options:

* `fast-open;host=example.shadowsocks.org;path=/video;tls`
* `fast-open;host=example.shadowsocks.org;path=/video;server`

```
https://example.shadowsocks.org {
 root /var/www/html/
 log access.log
 tls {
  dns cloudflare
 }

 proxy /video http://localhost:1984 {
  websocket
  transparent
 }
}
```

Note that server operates in HTTP mode and client in TLS.

**Comment by liudongmiao** [comment]
@Mygod As v2ray-plugin is unavailable on OpenWrt or other router-based systems.

So, I think it should be a plugin in c. I have implemented a simple one without mux support.

However, as `v1.mux.cool` in v2ray is not easy to implement, so I think there is a better way.

1. There are 3 rsv bits in websockets, we can make up to 8 channel.
2. There are 10 reserved opcode, we can use a opcode for close.
3. heartbeat use websocket's native ping / pong.

If mux is zero, it's compatible with v2ray-plugin.

And even more, we can just make masking key to 0...avoid mask the client request.

**Comment by UjuiUjuMandan** [comment]
@madeye 

> Yes, we should deprecate simple-obfs.

Sorry for late, but what about Session Ticket obfuscation? V2Ray never implemented it.
