### ISSUE TITLE
Feature request: Not to encrypt

### ISSUE THREAD

**Issue by liberal-boy** [shadowsocks/shadowsocks-org#140]
Some plugins have already encrypted the payload, such as: [kcptun](https://github.com/shadowsocks/kcptun), [v2ray](https://github.com/shadowsocks/v2ray-plugin). When using these plugins, the encryption of shadowsocks seems to be unnecessary. I think shadowsocks should allow users to choose not to encrypt. It is very helpful for low-performance and mobile devices.

**Comment by madeye** [comment]
You can just use rc4-md5, its performance is very close to the "non-encryption".

**Comment by liberal-boy** [comment]
@madeye thanks.
