### ISSUE TITLE
Shadowsocks can be detected now

### ISSUE THREAD

**Issue by hulb** [shadowsocks/shadowsocks-org#147]
I'm in Shanghai, China.
Recently I change my VPS location to get a new IP address since the old IP is not accessable from mainland of China.And I use latest image of shadowsocks-libev on the server side and shadowsocks-windows of version 4.1.6 which is the latest release on the client side.Today I start to work in my office and use them normally and suddenly the shadowsocks-windows cannot connect to the server and ping is not accessable for the server IP.And when I quit the client, few minutes later, server IP can be reached again.Ping is accessable but ssh is not response.

I just use the method: aes-256-gcm and no other plugin.

By the way before this block event, my old IP address is accessable when I was at home and not when I was in my work office.It might be that the company in mainland of China use a special network which can be applied some kind of block strategy  since it's the same network provider at home and in my work office.

So I'm confident in that the shadowsocks protocol can be detected by the GFW now.

Areyou aware of situation like this? And do you have solution for this?

**Comment by WalkerWalker** [comment]
https://censorbib.nymity.ch/pdf/Deng2017a.pdf
https://ieeexplore.ieee.org/abstract/document/8676111

a line of research is working on it. of course it will be detected sooner or later

**Comment by 8x8-64** [comment]
文章里一种分析是分析打开特定热门网站时最初10几个数据包的大小、方向、间隔等信息，这是可以通过伪造流量干扰分析，破坏特征的。一种是分析访问dns频率、突发流量频率、大小，辅助判断是否因为是代理导致流量集中，这个可以用多端口负载均衡干扰分析

**Comment by 8x8-64** [comment]
以上对抗手段可以在不改变现有ss协议达到，只要改变ss程序。举几个例子
1、服务器要断开连接，可以是直接断开tcp，也可以是发个错误的加密包，变成让客户端主动断开，这个加密包可长可短，数量可多可少，而且改变了流量方向，从而改变了流量特征。
2、使用AEAD加密时，要验证长度和内容，等于是2个条件。其实伪造数据包要满足其中一个条件都是做不到的，这是可以利用这点，如果长度正确，内容错误，就是故意伪装的数据包，直接丢弃而不断开。就可以伪造流量了。某些开发者坚持有错误数据包就应该断开，这根本就不是协议的要求，只是他的做法而已，自己给自己带脚镣。
3、论文里的实验环境是理想的，低延迟，非高峰期的。但是实际网络环境会出现堵塞，数据会粘包、丢包，导致包大小、间隔分布变化。程序在发数据包时动态调整缓冲区大小，就可以人为产生波动。
4、单机多端口负载分配，用iptables转发流量就行。
以上都不涉及协议更改，只是实现协议的方式不同，但是能有抗干扰效果。现在就是gfw知道你有异常大流量，但是不敢滥封杀。不然会有更多翻墙都躲到https协议里，就更难封杀了。

**Comment by WalkerWalker** [comment]
我們作為用戶，也很期待ss server, ss client都有一定的改進啊。

**Comment by 8x8-64** [comment]
自己改程序或者转投别的工具。现在的ss开发者在墙外，没有代理机ip被封的烦恼，不需要对抗封锁、干扰上网，只是做些修补，在ss流量被逐渐识别的形势下无动于衷。

我用自己的程序，9月这波没事
