### ISSUE TITLE
spec: include xchacha20-ietf-poly1305 (AEAD_XCHACHA20_POLY1305)

### ISSUE THREAD

**Issue by Artoria2e5** [shadowsocks/shadowsocks-org#149]
I doubt if this merits a specific SIP, as this has been implemented by a whole bunch of clients anyway. It is provided whenever libsodium wants to provide it, and has all the same parameters as chacha20-ietf-poly1305 besides a larger nonce.

Since Shadowsocks uses a non-random nonce anyway, the actual use of switching to this algorithm is questionable as increasing the size is only meant to reduce collision danger for random nonces. There is, fortunately, no performance penalty in using it. As such I suggest defining it to "may" or "should".

> Implementations may also support AEAD_XCHACHA20_POLY1305.
>
> Name | Alias | Key Size | Salt Size | Nonce Size | Tag Size
> -- | -- | -- | -- | -- | --
> AEAD_XCHACHA20_POLY1305 | xchacha20-ietf-poly1305 | 32 | 32 | 24 | 16
> 

(Oddly enough, it *was* mentioned in SIP004. There's no formal ietf spec.)

**Comment by riobard** [comment]
No. The goal is to simplify as much as possible by eliminating unnecessary choices.
