### ISSUE TITLE
What's the padding mode of stream ciphers ?

### ISSUE THREAD

**Issue by GreatFireWall** [shadowsocks/shadowsocks-org#151]
I don't see any information about padding mode at https://shadowsocks.org/en/spec/Stream-Ciphers.html

**Comment by lcdtyph** [comment]
It uses PKCS#5 (aka the standard block padding).

**Comment by GreatFireWall** [comment]
> It uses PKCS#5 (aka the standard block padding).

After read the source, I don't think so.

https://github.com/shadowsocks/shadowsocks-windows/blob/25e2b82a4a6f66cad0459c1cb292e2f1eace2d46/shadowsocks-csharp/Encryption/Stream/StreamOpenSSLEncryptor.cs#L93

**Comment by lcdtyph** [comment]
@GreatFireWall 
That's a mistake in source code.

Actually `cfb` and `ctr` mode don't use the padding parameter as ciphers that use these modes always produce same length as the plain texts. That is the reason why the code still works with ss-server. You can look at the mbedtls engine, they didn't set padding there.

If they add `cbc` mode ciphers support, then they must change that line.

**Comment by lcdtyph** [comment]
I've just noticed that shadowsocks does not support `cbc` ciphers anymore, which I thought it supported, did i misremember?

Then there is nothing to do with paddings since the currently supported stream ciphers will ignore that parameter.

**Comment by Mygod** [comment]
All stream ciphers are deprecated and only kept for legacy reasons. Avoid using it at all costs.

**Comment by GreatFireWall** [comment]
> All stream ciphers are deprecated and only kept for legacy reasons. Avoid using it at all costs.
> 
> EDIT: Just in case you are oblivious, replacements are [AEAD ciphers](https://shadowsocks.org/en/spec/AEAD-Ciphers.html).

Be that as it may, most service providers use old ciphers, because they deploy forward server in China, so rc-md5 works well for me a long time.

So I think more is the network path reason, not the algorithm.
