### ISSUE TITLE
[非Issue]这个人是谁？

### ISSUE THREAD

**Issue by ohsorry** [shadowsocks/shadowsocks-org#158]
我指的是这个人studentmain.

[https://github.com/shadowsocks/Shadowsocks-Net/commit/33cd9158e65e2258d5d1026637398525ce038002#commitcomment-37824437](https://github.com/shadowsocks/Shadowsocks-Net/commit/33cd9158e65e2258d5d1026637398525ce038002#commitcomment-37824437)

我从最初设计并编码了Shadowsocks-Net（出于对ss的兴趣），也一直我一人在码代码（虽然我邀请了他和celeron533来添加代码）。

这个人对于我写的程序只干了两件事：
1.几天前突然给标上了项目介绍：Experimental .NET Core implementation for Shadowsocks
尽管我在readme里写的是可用于测试了，而且都没发release。
2.发了一个没任何营养的issue，对话全是废话，我后来删掉了。不过我删除之前保存pdf了。

后来发生了最开始一幕，他直接修改了master分支的代码，原因是一个我没发现的typo：英语单词少了一个字母。

为什么是这样的人在shadowsocks的开源社区做维护？大概翻看了下他/她最初对shadowsocks-windows的提交：改了两三行代码：换了语法糖。

**Comment by madeye** [comment]
As per the audit log, he is an outside collaborator of your repo and shadowrocks-windows.

I think you can discuss with him directly about how to maintain your project in a proper way.

**Comment by Mygod** [comment]
I don't see there is an issue as there is no malicious behavior.

**Comment by ohsorry** [comment]
Already talking to him:
[https://github.com/shadowsocks/Shadowsocks-Net/commit/33cd9158e65e2258d5d1026637398525ce038002#commitcomment-37824437](https://github.com/shadowsocks/Shadowsocks-Net/commit/33cd9158e65e2258d5d1026637398525ce038002#commitcomment-37824437)

I feel that this guy is dominant and lacks respect for others.

**Comment by madeye** [comment]
Communication is important.

Please make sure you guys have a good discussion on the development plan and methodologies.

Private and direct discussion is always preferred, to avoid this kind of off-topic issues here.

**Comment by ohsorry** [comment]
To clarify my thoughts: I designed and coded this project from the very beginning,
he should submit the code through PR. I would be happy for someone to implement this project together.
If he thinks the project design or code is bad, point it out.
I am an easy to talk person.
I will close this issue if it is resolved.

**Comment by ohsorry** [comment]
Thank you for your time and open mind. 🍺

**Comment by studentmain** [comment]
> submit the code through PR

如我回复的，你需要设立PR规则，为了保证PR质量，code review也是必要的。见https://github.com/shadowsocks/Shadowsocks-Net/commit/33cd9158e65e2258d5d1026637398525ce038002#commitcomment-37825314

> project design

已经说明过在已有外部插件机制的情况下增加混淆是浪费，https://github.com/shadowsocks/shadowsocks-windows/issues/2756#issuecomment-586687938 。出于只能有一个地方加混淆的考虑，建议提交标准化以避免出现不统一的情况。

基于同一个issue下的讨论，放弃WinForm界面，替换为WPF界面。

**Comment by studentmain** [comment]
> 为什么是这样的人在shadowsocks的开源社区做维护？

因为真的没人了。你别看有些项目热闹得很，背地里写代码的只有3个（半年前只有1个）。

**Comment by ohsorry** [comment]
你有想法可以自己重构开仓库，如果你的设计优秀，我给你提交PR好吧。你直接改master产生冲突不知道你什么目的。你应该能看到UI我已经用winform设计完了，所以不计划用WPF了，这个程序的UI不是重点。

关于你说的什么混淆的“标准化”，我在设计上就考虑了，而且扩展很方便。所以不需要外部程序。也不是什么复杂设计和特有的功能，仍然兼容外部“插件”。

开源不是为你个人写的，也应该让别人有贡献的机会，那怕一个提议。什么都你说了算没得商量有人来维护才怪。

**Comment by studentmain** [comment]
> 你有想法可以自己重构开仓库

我有什么想法我开了什么仓库不重要，争执出现在你的想法和你的仓库。

> 不是什么复杂设计和特有的功能
 
特有功能，指只有某些实现上才有的功能。显然只有 Shadowsocks-Net 拥有不使用插件进行混淆的功能，因此我认为这是特有功能。

> 什么都你说了算没得商量

以上内容可都不止我一个人说过，有一些甚至在几年前就达成共识了。

**Comment by ohsorry** [comment]
所以你提交master产生冲突？

**Comment by studentmain** [comment]
如果你不愿意别人直接碰你的代码，可以设立PR规则。

**Comment by ohsorry** [comment]
因为没设定社么规则，假设周围的人没人品问题，所以你提交冲突？

**Comment by ohsorry** [comment]
> 几年前就达成共识

重构不能有任何创新？必须翻新一遍？让我怀疑不是人品问题，是特么智力问题。

**Comment by studentmain** [comment]
Collaborator角色具有直接向master推送的权限，在你邀请任何人参加项目之前应该知晓。同时，你往master上直接push是否可以说它对我的更改会造成冲突呢。
基于我直接向master上推送的事实，你是否假定我人品有问题？如果有，可否说明是什么问题以便改进？

那个共识包括完全把混淆交给外部插件，程序本体不做任何处理。

**Comment by wangxufire** [comment]
> > 几年前就达成共识
> 
> 重构不能有任何创新？必须翻新一遍？让我怀疑不是人品问题，是特么智力问题。*。

ss都有相关标准定制得，SIP003。你要实现ss协议又不想按照标准来。

**Comment by ohsorry** [comment]
steram cipher挺好的啊，为什么淘汰呢？

**Comment by studentmain** [comment]
> steram cipher挺好的啊，为什么淘汰呢？

基于已有事实达成了新的共识，对标准重新进行了讨论。这也是我提议把你的想法拿出来讨论形成新的标准的原因。

**Comment by ohsorry** [comment]
现在的也能用，为什么要设计v2协议呢？
 这个仓库是celeron533给建的用来重构的，我也没邀请啊？

**Comment by Mygod** [comment]
Guys if you actually have something productive to discuss, please open a separate issue (also one issue for one topic please, not a mess like this); otherwise, please take the heated argument elsewhere, maybe [discourse.shadowsocks.org](https://discourse.shadowsocks.org/).
