### ISSUE TITLE
Proposal for a new backward-compatible ss protocol

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-org#16]
The current ss protocol doesn't include One-Time Authentication feature which is essential to make a proper connection. I propose two possible solutions to this problem.

Here's a regex for current protocol which doesn't include OTA:

    (?i)^ss://((?<method>.+?):(?<password>.*)@(?<hostname>.+?):(?<port>\d+?))$
    (?i)^ss://(?<base64_encoded_group_1>.+)$

And these are two possible upgrades that are backward compatible for the ones that haven't enabled OTA where `-auth` is appended to method:

    (?i)^ss://((?<method>.+?)(?<auth>-auth)??:(?<password>.*)@(?<hostname>.+?):(?<port>\d+?))$
    (?i)^ss://(?<base64_encoded_group_1>.+)$

Or `?auth` or `/?auth` is appended to the end of URL:

    (?i)^ss://((?<method>.+?):(?<password>.*)@(?<hostname>.+?):(?<port>\d+?))/??(?<auth>\?auth)??$
    (?i)^ss://(?<base64_encoded_group_1>.+)/??(?<auth>\?auth)??$

I prefer the first one. What do you think?

**Comment by Mygod** [comment]
[Figure for my preferred approach](https://www.debuggex.com/r/xRVLQnl3rNP4IXjq).

**Comment by librehat** [comment]
I think the latter one with `/auth` appended is better and easier to adapt.

**Comment by Mygod** [comment]
It's `/?auth` or `?auth`. The path segment isn't usually used for authentication in URI conventions.

**Comment by madeye** [comment]
I prefer `-auth`, as it's part of encryption method of shadowsocks protocol.

**Comment by librehat** [comment]
Okay, but it might break old clients since they won't check whether encryption method ends with `-auth`

**Comment by Mygod** [comment]
@librehat Old clients won't be able to connect if they don't know OTA is enabled anyway. And the latter one will also result in a parse error in shadowsocks-android port.

**Comment by librehat** [comment]
`-auth` appended to encryption method then. I'm OK with it.

**Comment by Mygod** [comment]
I'm only updating `shadowsocks-windows` and `shadowsocks-android` branch to support this protocol. Other project maintainer can update their related code imitating https://github.com/shadowsocks/shadowsocks-windows/pull/538.
