### ISSUE TITLE
Upgrade source to 2.4.5

### ISSUE THREAD

**Issue by blackgear** [shadowsocks/shadowsocks-org#17]
Version 2.4.0-1 is outdated and insecure and there are two high urgency updates according to the changelog.

> shadowsocks-libev (2.4.1-1) unstable; urgency=high
> * Fix a security bug.
>
> shadowsocks-libev (2.4.3-1) unstable; urgency=high
> * Refine the buffer allocation.

Maybe you could add a separated source for Jessie by the way.

**Comment by madeye** [comment]
https://github.com/shadowsocks/shadowsocks-libev#install-from-repository

**Comment by Mygod** [comment]
Maybe we should remove `Install from repository` section?

**Comment by madeye** [comment]
I think Debian users can directly install from "official " repository?
