### ISSUE TITLE
设计新的 UDP 传输格式，原生支持多倍发包、长度填充

### ISSUE THREAD

**Issue by rprx** [shadowsocks/shadowsocks-org#174]
Shadowsocks 对 UDP 流量的代理仍基于 UDP，保留了纯粹的 UDP 特性，相对于其它协议的 UoT，这非常难得。
因此，很多人用 SS 来加速游戏，但 UDP 丢包问题会严重影响体验，已有解决方案如 [UDPspeeder](https://github.com/wangyu-/UDPspeeder/blob/branch_libev/doc/README.zh-cn.md)
而运载游戏的 UDP 包，带宽完全不是问题，所以若引入简单的多倍发包策略，即可极大改善 UDP 丢包问题。

最粗暴的方法是直接将密文发送多次，或者将载荷加密多次，但前者长期易被识别，后者则对应用不透明（甚至可能导致封号）
所以更合适的方向是设计新的 UDP 传输格式：明文部分新增 **唯一标识符** 和 **可选长度填充**，且需要炸掉原本的格式解析器。
设想是服务端可以同时兼容现有格式与新格式，且尽量避免现有格式的潜在问题。@madeye @mygod @riobard

**Comment by riobard** [comment]
I'm afraid that speeding up UDP is unlikely a design goal of this project.
