### ISSUE TITLE
 How to  generate master key from password?

### ISSUE THREAD

**Issue by totravel** [shadowsocks/shadowsocks-org#179]
About the master key, paper only says 'can be generated from a password', but how?

**Comment by DuckSoft** [comment]
You want to see HKDF.

**Comment by totravel** [comment]
I got the answer here: https://github.com/shadowsocks/shadowsocks-go/blob/3e585ff90601765510d31ee1d05b6f63548c7d44/shadowsocks/encrypt.go#L35-L36

Example in node.js:

```javascript
const passwd = '123456';
const crypto = require('crypto');
const hash = crypto.createHash('md5');
const tmp = hash.copy().update(passwd).digest();
hash.update(Buffer.concat([tmp, Buffer.from(passwd)]));
const key = Buffer.concat([tmp, hash.digest()]);
console.log(key);
```
