### ISSUE TITLE
Proposal for a random encrypt method

### ISSUE THREAD

**Issue by ayanamist** [shadowsocks/shadowsocks-org#19]
Idea from TrueCrypt.

A new method called random, which client establishes a connection using a random-selected method of all widely available methods, and server decrypt the first bytes (270 bytes at most), and try every method to decrypt it, then use same method to decrypt remaining bytes.

Pro:
1. Obfuscate data flow on one server port.
Cons:
1. More flow when being attacked
2. Will cost much more CPU when accepting connections.

**Comment by librehat** [comment]
Unnecessary overhead for the protocol without any obvious benefits. Again, the encrypted data in shadowsocks is not possible to decrypt without knowing the method and key.

If the key is compromised, this method doesn't really work since you have the method in datagram.

**Comment by ayanamist** [comment]
It emphasis on dataflow obfuscation in order to decrease the risk of being detected by dataflow analysis, but not on encryption itself.
By changing method for each connection, it will increase much more chance to survive. There are reports that the ip port used as ss will be slow down or blocked after some time usage.

**Comment by madeye** [comment]
To me, it looks no helpful to obfuscate data in that "random" way. Instead, it will introduce great overhead on server side.

The state-of-the-art way of obfuscation is obfsproxy, which hides encrypted traffic in "normal" traffic, not "random" traffic. So, if you really want to obfuscate traffic of shadowsocks, obfsproxy is a better choice.

**Comment by ayanamist** [comment]
I know you guys want to keep UNIX philosophy, but don't concern only on self-hosted. There is no selling ones which provides additional protect for shadowsocks like obfsproxy.

**Comment by madeye** [comment]
I think it has nothing to do with UNIX philosophy.

As mentioned above, the major concern from us is that your proposed random approach may not help to obfuscate traffic but introduce large overhead. Actually, IV in shadowsocks protocol is just for randomizing keys. And it works quite well.

**Comment by ayanamist** [comment]
No, neither IV nor OTA will remove or decrease the traffic characteristic of shadowsocks connection.

**Comment by sorz** [comment]
I don't think difference exists among different ciphers, in terms of "traffic characteristic".
AFAIK, they all keep generating (pseudo) random bits and then XOR with plaintext.

**Comment by Mygod** [comment]
Veto on this proposal. Actually why isn't this closed yet?

**Comment by madeye** [comment]
Closed as we have https://github.com/shadowsocks/shadowsocks-org/issues/26 now.
