### ISSUE TITLE
弱弱的问一句，啥是SIP？

### ISSUE THREAD

**Issue by e1732a364fed** [shadowsocks/shadowsocks-org#198]
抱歉，我是新手，刚准备研究ss。我看有的issue有 [SIP] 字样。这个是什么呢？看起来似乎是 “标准修订案”的感觉，但是又没在 什么地方看到需要标 “SIP” 这种要求。

有没有懂的讲一下这个是什么来历呢

还有各种 SIP002，SIP022 这种情况，看起来好吓人，不知为何有点像监狱的人的衣服上的号码？？

**Comment by lzm0** [comment]
Shadowsocks Improvement Proposal

**Comment by e1732a364fed** [comment]
哦哦谢谢。不过还是想问一下，出处在哪里呢？谁规定的呢？

主要是，我想用 [IP] ，或者 [Amends] 之类的作为前缀。

**Comment by lzm0** [comment]
> 哦哦谢谢。不过还是想问一下，出处在哪里呢？谁规定的呢？
> 
> 主要是，我想用 [IP] ，或者 [Amends] 之类的作为前缀。又怕别人说不符合规定。但是问题是我似乎找不到什么 规定

It's just a convention, like Bitcoin Improvement Proposal or Ethereum Improvement Proposal.

**Comment by e1732a364fed** [comment]
哦哦哦，原来如此，原来是国际惯例啊，懂了。谢谢！
