### ISSUE TITLE
社区有没有针对SIP023 relay server  的开发计划

### ISSUE THREAD

**Issue by oujl** [shadowsocks/shadowsocks-org#240]
SIP023 的标准非常适合我目前的需求，rust ss-local 已经兼容这个标准，但是我没有找到专用的 relay server实现，咨询一下有没有开发计划，我是一个客户端的个人开发者。搞不定这个东西 ，如果没有开发计划，有兴趣做这个事情的小伙伴可以联系一下我。我可以提供一些赞助,且开源

**Comment by database64128** [comment]
https://sing-box.sagernet.org/examples/shadowsocks/#relay

**Comment by oujl** [comment]
好的。谢谢你提供的信息 。@database64128
