### ISSUE TITLE
Proposal for a new SS URL schema with tag/remark

### ISSUE THREAD

**Issue by madeye** [shadowsocks/shadowsocks-org#25]
As discussed in https://github.com/shadowsocks/shadowsocks-android/issues/989#issuecomment-263112168, we may use # for tag/remark in the SS URL schema. For example:

```
(?i)^ss://((?<method>.+?)(?<auth>-auth)??:(?<password>.*)@(?<hostname>.+?):(?<port>\d+?))(#(?<tag>.+?))*$
(?i)^ss://(?<base64_encoded_group_1>.+)$
```

For more details: https://www.debuggex.com/r/y70l3GyYFSoim4Uc

**Comment by Mygod** [comment]
```
-(?i)^ss://((?<method>.+?)(?<auth>-auth)??:(?<password>.*)@(?<hostname>.+?):(?<port>\d+?))(#(?<tag>.+?))*$
+(?i)^ss://((?<method>.+?)(?<auth>-auth)?:(?<password>.*)@(?<hostname>.+):(?<port>\d+))(#(?<tag>.+))?$
```

Also, should `#tag` be included in `base64_encoded_group`? How about this:

```
(?i)^ss://(?<base64_encoded_group_1>.+)(#(?<tag>.*))?$
```

**Comment by madeye** [comment]
I prefer to not appending tag after `base64_encoded_group`, as it would cause duplicates.

**Comment by Mygod** [comment]
I meant including the tag only after #.

**Comment by madeye** [comment]
Hmm, I'm not sure. It there any good reason to do that?

**Comment by Mygod** [comment]
Because that's technically a URL fragment and can be choosed arbitrarily?

**Comment by madeye** [comment]
Sounds good. Let's take the second proposal.

**Comment by Noisyfox** [comment]
Why don't encode tag in qr code?

**Comment by madeye** [comment]
I'm convinced by this https://github.com/shadowsocks/shadowsocks-org/issues/25#issuecomment-263174246

**Comment by Noisyfox** [comment]
I mean the qr code could contain the tag either, so that someone shares a ss url with tag via qr code and I don't need to name that server again.

**Comment by madeye** [comment]
QR code also has the tag. It only depends on what's the URL encoded in the QR code.

**Comment by Noisyfox** [comment]
Hm, alright because the example qr code on https://shadowsocks.org/en/config/quick-guide.html doesn't contain a tag but the url right above does.

The reason I asked these question is I'm not sure if it's ok to encode remarks as tag in the qr generator which could cause some compatibility issues.

**Comment by wongsyrone** [comment]
It will be better if you clarify utf-8 encoding is needed.

ref: https://github.com/shadowsocks/shadowsocks-android/commit/357130cda08ae67a6f6d7e63a5405730e5614802

**Comment by Mygod** [comment]
That should be a convention. :p (I mean what else would you use)

**Comment by wongsyrone** [comment]
Just a suggestion, all up to you guys.
