### ISSUE TITLE
SIP005 - TCP MD5SIG to counter TCP RST MitM attack

### ISSUE THREAD

**Issue by anonymous-contributor** [shadowsocks/shadowsocks-org#32]
# Backgroud
Although we have Tor PT support (only proxy mode yet), someone may consider it's too heavy.

The original purpose for Tor PT support is to avoid TCP RST Man-in-the-middle attack, for some it's too heavy and considering there is already some report about DPI devices [detecting obfs2/3/4 or screamblesuit](https://www.allot.com/products/platforms/supported-protocols/#1460974307058-a61550f0-8196), another lightweight implement won't hurt.

# Lightweight alternative
And I just found that there is already [RFC 2385](https://www.ietf.org/rfc/rfc2385.txt) addressing this problem by introducing MD5 signature for TCP.
Which even covers TCP handshake, making it quite a good option for us to simply defend TCP RST MITM attack.

Furthermore, this option will only work if we use plain SS.
If we're using SIP003 plugin, such MD5SIG should be disabled as we're just wasting our CPU on localhost communication.

# Further concern
The implementation should be even easier than Tor PT proxy mode, but I still have several concern on it.

1. Insecure hash algorithm
There is known attack against MD5, it's no longer considered as a safe hash algorithm.

2. More obvious connection characteristic
MD5SIG is normally strongly binded to BGP, which is far from common in normal use case.
Use of MD5SIG will make connection super easy to be detected and blocked.

3. Harder to debug
Since kernel will just drop any TCP packet with wrong or no MD5 signature, including the hand shake packets, withouth informing user space, it will be quite hard to debug.

So I think it's better to be discussed before pushing a PR.

**Comment by Mygod** [comment]
Despite the insecure MD5 problem, can TCP_MD5SIG be used on Windows? I suspect it. I've searched for a while and have found none so far. We need a cross platform solution.

In order to [defend TCP against spurring attacks](https://tools.ietf.org/html/rfc4953), we need to somehow authenticate the TCP header. I think @clowwindy has already pointed us the direction with [ShadowVPN](https://github.com/clowwindy/ShadowVPN/tree/17f86cc8cfc54b39333e645c6031f7daee35b912).

**Comment by anonymous-contributor** [comment]
@Mygod OKay, I just forget there are Windows users.

Although it's more-or-less the same suituation for multipath TCP, or even TCP fast open.
Multipath TCP is even not supported in mainline linux, and Windows doesn't support fast open until Windows 10.

While they are both supported by ss-libev. 
Although TCP_MD5SIG, unlike MPTCP or fast open, will cause network stack to directly drop unauthenticated segments without fallback method.

Any authentication against TCP or IP header has their problem in fact.
They both exposed special flag for their header, making it quite easy to be detected and blocked.

**Comment by Mygod** [comment]
Yes and so we can use UDP to work around this problem. (ShadowVPN tunnels IP packets over UDP)

I think for now using [kcptun plugin](https://github.com/shadowsocks/kcptun) is the best choice to work around TCP reset attacks.

@madeye What do you think?

**Comment by madeye** [comment]
TCP reset attack is already not a "popular" approach. Today, If one IP gets detected, all the traffic from it is just dropped or null routed.

But like MPTCP and TCP fast open, if we can easily add it to shadowsocks, I think it would be useful to someone.

For example, with MPTCP, OVH is able to provide a product named "Overthebox" based on shadowsocks. It's quite useful if you have multiple up-links. Here are some details: http://bitsofnetworks.org/ovhs-overthebox-internet-access-link-aggregation-using-multipath-tcp.html

![image](https://cloud.githubusercontent.com/assets/627917/22538662/10b058ac-e94f-11e6-957b-ad87bd99ff05.png)

**Comment by anonymous-contributor** [comment]
@Mygod Makes sense.

There are a lot of advantage using UDP, from full control of the stack to no need to wait kernel to accept some feature.

@madeye For implementation, it should be quite easy. Both client and server setup their pre-shared key(could just hash the password), call setsockopt(),  ~~~and hope everything works fine~~~ that's all.
At least for linux kernel, it's more popular than TCP fast open.

I'll wait for some time before sending out the patch, to see if it's really needed.

Thanks

**Comment by riobard** [comment]
The downside of UDP tunneling is that UDP packets are dropped and traffic-shaped heavily on many ISPs. It's barely usable during peak hours when ISPs giving higher priority to TCP packets.

**Comment by Hexcles** [comment]
I worked with TCP_MD5SIG (on the kernel side) at a network switch company a while ago. There is a huge limitation here to be kept in mind: TCP_MD5SIG (RFC 2385) was invented to protect protocols like BGP -- where ports of both clients and servers are known and fixed, so the _implementations_ (Linux for example) require users to bind on **both** client and server sides, and provide the `<key, peer sockaddr (addr+port)>` mappings to kernel. And no, it does not support "default key" lookup. In the context of common C/S architectures like Shadowsocks, the client address and port are unknown in advance, rendering this protection useless at least on Linux.

Furthermore, as one might have noticed, MD5 is dated and in fact, RFC 2385 has been obsoleted by [RFC 5925](https://tools.ietf.org/html/rfc5925), TCP-AO, which unfortunately is not yet supported on consumer OSes AFAIK. Being an obsolete (and _undocumented_) feature, MD5SIG might be removed from Linux kernel at any time.

Here's a useful article I found talking from the userland if you are interested https://criticalindirection.com/2015/05/12/tcp_md5sig/

**Comment by riobard** [comment]
@Hexcles So this proposal is dead end?

**Comment by Hexcles** [comment]
Oh forgot my conclusion. In short, I don't think it's practical generally.

The only way to make use of MD5SIG is to configure client(s) in the server
configuration, and to bind to specific port on the client side (not the
listen port, but the port used to talk to server), which effectively makes
SS a site-to-site tunnel instead of "road warriors".

That said, I agree it is a useful defense against forged RST, and probably
the only one if we use vanilla TCP (without IPsec etc), unfortunately. If
one is convinced it is a real use case, they may want to fork SS to
experiment.

**Comment by riobard** [comment]
Understand. Thanks for the explanation! 

I really wish it'd be easier to manipulate raw IP packets from userspace…

**Comment by Mygod** [comment]
I think it's safe to close this now.
