### ISSUE TITLE
Review my new Go port

### ISSUE THREAD

**Issue by riobard** [shadowsocks/shadowsocks-org#38]
Initial attempt only included AEAD support. I rushed to add back the original stream ciphers. Now it's usable (only a few modern ciphers included; deprecated ones are left out), but lacks polish and usage documentation. Will follow up on that next. 

To experiment, run `go install github.com/riobard/go-shadowsocks2`. Currently it supports SOCKS5 proxy, Netfilter TCP redirect (IPv6 support included but not tested), UDP and TCP tunneling. 

Please review and criticize.

Code at https://github.com/riobard/go-shadowsocks2
Godoc at https://godoc.org/github.com/riobard/go-shadowsocks2

**Comment by madeye** [comment]
Cool! I've to say Go is really the best language for network application.

**Comment by madeye** [comment]
If you'd like to move this repo to shadowsocks-org, please let me know.

**Comment by riobard** [comment]
There's still polish work to do, and I haven't tried interoperability with shadowsocks-libev yet. I'll let you know when it's ready.

Also, if we move it to the org, what to do with the old Go port which I believe @lixin9311 is working on to refactor.

**Comment by madeye** [comment]
I think you may open an issue on shadowsocks-go and discuss this with @lixin9311. It would be very nice if you can work together.

**Comment by bigtan** [comment]
@riobard As I know, many ss users use cow as shadowsocks client, could you make your golang port compatible with [cow](https://github.com/cyfdecyf/cow).

**Comment by riobard** [comment]
Interoperability with compliant implementations is a key goal.

**Comment by riobard** [comment]
@madeye I'm almost done. Can you try and see if my Go port works with your implementation? I don't have the environment to compile your latest libev port and I haven't found binary releases yet.

I've tested my Go port with libev port using stream ciphers and they work fine.

**Comment by madeye** [comment]
@riobard OK. Let me do the tests.

**Comment by madeye** [comment]
Stream ciphers work well. However, all the AEAD ciphers don't work.

I tried looking into https://github.com/riobard/go-shadowsocks2/blob/master/shadowaead/packet.go, and cannot figure out how it handles DataLen and DataLen.TAG. Does it follow our chunk design in SIP004?

**Comment by madeye** [comment]
OK, it's my problem. Everything works now.

**Comment by riobard** [comment]
Great! I believe the new Go port can be included in the org now as it's functionally completed and about feature-parity with the libev port. 

Do I fork it into the org?

**Comment by madeye** [comment]
Two options:

1. Transfer your repo to the organization. https://help.github.com/articles/about-repository-transfers/
2. Fork your repo from organization.

Both should work.

**Comment by riobard** [comment]
I'd pick 2, otherwise I'll have to fork it back into my account (which is silly) 😂 

Do I need to be granted write access to the org?

**Comment by madeye** [comment]
Not sure. I just forked it for you.

**Comment by riobard** [comment]
Thanks! :)

**Comment by simonsmh** [comment]
Would you please add config.json support?

**Comment by madeye** [comment]
I think we're done here. Please open any further issue on that repo instead.
