### ISSUE TITLE
Does Shadowsocks have property of forward secrecy after adding SIP004 and SIP006?

### ISSUE THREAD

**Issue by hellofwy** [shadowsocks/shadowsocks-org#39]
If the password which is user provided or randomly generated by Shadowsocks is disclosed in future, does it can be used to decrypt the already transferred messages which are recorded by a third party?

**Comment by madeye** [comment]
Yes, if your key is disclosed, the traffic can be decrypted by thrid-party.

But the good news is it's almost impossible to brute-force a 32-byte random key. That's why we have SIP006.

**Comment by hellofwy** [comment]
My concern is that relatively big public Shadowsocks servers will draw more attentions and their security may not be as strong as we think.
However may be I'm a little too worried.
