### ISSUE TITLE
Experimental AES-SIV cipher

### ISSUE THREAD

**Issue by riobard** [shadowsocks/shadowsocks-org#41]
I've added an experimental AES-SIV cipher to my Go port here https://github.com/riobard/go-shadowsocks2/commit/7bcc772175818a48a9de3f8eeed69652b68a586a

This should in theory mitigate the issue of nonce reuse in SIP004 since SIV is misuse-resistant. However the performance of SIV is pretty bad, as SIV is a non-online 2-pass cipher. 

Benchmarking on my machine using AES-SIV-512 results in ~1Gbps throughput measured by iperf3, compared to >4Gbps throughput using AES-256-GCM. In most cases 1Gbps is more than good enough.

**Comment by madeye** [comment]
I'm considering AES-GCM-SIV: https://tools.ietf.org/html/draft-gueron-gcmsiv-00

According to https://eprint.iacr.org/2015/102.pdf

>  Table 2 shows that GCM-SIV is 14% slower than AES-GCM on Haswell, and 19% slower than AES-GCM on Broadwell

Also, we have an open source implementation here:

https://github.com/Shay-Gueron/AES-GCM-SIV

**Comment by riobard** [comment]
Looks very promising! I haven't found a native Go lib supporting AES-GCM-SIV, though.

**Comment by riobard** [comment]
SIV is no longer necessary once #42 is implemented. Closing now.
