### ISSUE TITLE
Request to add Perl Shadowsocks

### ISSUE THREAD

**Issue by zhou0** [shadowsocks/shadowsocks-org#46]
Hello!

I have contributed a Perl shadowsocks module ( client and server scripts included ) to CPAN at 
https://metacpan.org/release/Net-Shadowsocks

as of version 0.8.0, The following are part of the ciphers being supported: 
AES-128-CFB AES-128-CTR AES-192-CFB AES-192-CTR  AES-256-CFB AES-256-CTR 
Camellia-128-CFB Camellia-192-CFB Camellia-256-CFB 
Chacha20-IETF 
RC4-MD5 

Please visit https://metacpan.org/release/Net-Shadowsocks to see a full list of supported ciphers.  Supporting AEAD cipher is planned.

Is it O.K. for you guys to add this Perl implementation ( both client and server ) on your website?

**Comment by madeye** [comment]
Cool! Do you have a project on Github?

To add your project to the web page, please open a pull request here.

**Comment by zhou0** [comment]
it is imported to https://github.com/zhou0/shadowsocks-perl
