### ISSUE TITLE
Is there any plan to support multiple users on single port?

### ISSUE THREAD

**Issue by yjsslab** [shadowsocks/shadowsocks-org#49]
as a standard in the new version protocol

**Comment by riobard** [comment]
You mean multiple passwords/ciphers on the same port? It's not possible without changing the protocol.

**Comment by yjsslab** [comment]
What need to change except the config file?
if the change is not big, I think its acceptable in the new AEAD protocol.

**Comment by riobard** [comment]
It's more complicated than that. In short, a new protocol is required.
