### ISSUE TITLE
Why do we base64 encode Shadowsocks URL?

### ISSUE THREAD

**Issue by riobard** [shadowsocks/shadowsocks-org#50]
For example in https://shadowsocks.org/en/config/quick-guide.html

     ss://method:password@hostname:port

is base64 encoded to 

     ss://YmYtY2ZiOnRlc3RAMTkyLjE2OC4xMDAuMTo4ODg4Cg

**Comment by kimw** [comment]
For better exchange, I think.

The base64 encoded string is simple to handle than others.

**Comment by madeye** [comment]
The short story is we don't want the URL to be searchable, which seems not necessary today.

Then, it's been fixed via SIP002, https://github.com/shadowsocks/shadowsocks-org/issues/27

**Comment by Mygod** [comment]
We're actually changing that in one of the SIPs...

**Comment by riobard** [comment]
I don't get it. The base64 encoded "URI" still has the `ss://` scheme prefix, so still searchable? 

Just finished reading SIP002. Feels like this is still a work-in-progress? What's the plan? I was working on simplifying the command line arguments. Instead of taking separate arguments for cipher/password/host/port, it could take a plain URL as a whole, e.g. 

    go-shadowsocks2 -c ss://aes-128-gcm:your-password@[server_address]:8488

and then I'm puzzled by the base64-encoded format.

**Comment by madeye** [comment]
@Mygod has finalized the new schema in this comment: https://github.com/shadowsocks/shadowsocks-org/issues/27#issuecomment-272366304.

Now, only the cipher name and password are encoded in URL-safe BASE64 in case we need to support key file directly in the URL.

**Comment by madeye** [comment]
@riobard Hmm, most of search engine doesn't support search the URL schema directly, e.g. https://www.google.com.hk/search?q="ss%3A%2F%2F".

Anyway, I agree it's not necessary at all.

**Comment by riobard** [comment]
I see. Let's continue the discussion under SIP002.
