### ISSUE TITLE
Use the wiki to host development-related documents

### ISSUE THREAD

**Issue by riobard** [shadowsocks/shadowsocks-org#51]
I'm thinking about moving and organizing development-related documents (like protocol details, cipher nuances, etc). This makes it easier to track up-to-date changes.

**Comment by librehat** [comment]
I think it's a good idea. Then once it's finalised, we should also make sure it's updated on the website.

**Comment by riobard** [comment]
I guess it's probably easier to update the website with links pointing to the wiki instead of duplicating in two places. @madeye what do you think?

**Comment by madeye** [comment]
Yes, we can link spec to wiki instead.

**Comment by riobard** [comment]
I've rewritten the protocol document here https://github.com/shadowsocks/shadowsocks-org/wiki

**Comment by librehat** [comment]
GitHub doesn't optimise wiki pages for mobiles. 

It's not that difficult to duplicate them on the website...... Basically just copy and paste

**Comment by madeye** [comment]
No need to copy and paste, Just added the wiki repo as a submodule. https://github.com/shadowsocks/shadowsocks-org/commit/c7dd8b5ae7c6d13bf0a53bd70bb70126ef5e0b36

From now on, let's only update specs in the wiki pages. I'll occasionally run the grunt locally to update websites. (You can also run the grunt and submit a pull request)

**Comment by madeye** [comment]
One thing forgot to mention is new pages should be named as `NUM-Title`, e.g. `01-AEAD-Ciphers`.

**Comment by riobard** [comment]
@madeye Is there a way to automate the process? Like a webhook or something? 

Also, is the numbering for ordering?

**Comment by madeye** [comment]
> Is there a way to automate the process? Like a webhook or something?

No idea about it. But a cron job on my local machine should do the trick.

> Also, is the numbering for ordering?

Right.

**Comment by riobard** [comment]
@madeye Got it. 

Just a reminder here for anyone contributing to the wiki: when you change the page title, please remember to update links pointing to that page because the path will change as well.

**Comment by riobard** [comment]
@madeye Hmm, maybe we should learn something from the `shadowsocks` [wiki](https://github.com/shadowsocks/shadowsocks/wiki)? They ditched the pages sidebar and use their own Table of Content and sidebar.

It looks nicer and if we need to change ordering there's no need to update all old links. Thoughts?

**Comment by madeye** [comment]
Maybe the ordering on the website is not that important? If so, we can remove that numbers, the grunt will use alphabetical ordering instead.

**Comment by riobard** [comment]
@madeye It doesn't matter as of now. I'm just worried about the trouble of updating old links if we change page numbering.

**Comment by riobard** [comment]
Also, we need to refer to the wiki pages from other places. If we change the numbering, those links will break too. Better for the page titles to be as stable as possible.

**Comment by madeye** [comment]
OK, revert to old titles.

**Comment by riobard** [comment]
Close now that the wiki is the canonical version of protocol and cipher specs.

**Comment by Mygod** [comment]
Wait what's so bad about the old approach?

**Comment by riobard** [comment]
Simple. It's painful to make a commit and PR every time to just correct a typo. Using the wiki is much easier and faster.

**Comment by Mygod** [comment]
@riobard If you have push access you don't need to create a PR to fix a typo. If you don't, create a PR and create additional commits to fix typos in your changed lines. Simple.

**Comment by riobard** [comment]
@Mygod I know. The wiki is still easier 😊

**Comment by Mygod** [comment]
Okay. Good job on making @madeye's life a bit harder. :confused:

**Comment by riobard** [comment]
I thought it's making the process easier? 😂

**Comment by Mygod** [comment]
How is maintaining two copies easier than one copy?

**Comment by riobard** [comment]
The website now pulls the wiki as a git submodule. There's just one copy.

**Comment by Mygod** [comment]
Okay.

**Comment by Mygod** [comment]
Okay.

**Comment by riobard** [comment]
Is there  anyway to trigger the website to rebuild when the wiki changes? That'll make the task even easier.

**Comment by Mygod** [comment]
I don't think wiki supports webhooks. And even if it does, I prefer to using the website/main repo as a stable branch.

**Comment by riobard** [comment]
Ok. So we still follow the old approach. @madeye will occasionally rebuild the website. The wiki is for tracking latest changes (e.g. experimental features) that might not be ended up shipping. Looks good?

**Comment by Mygod** [comment]
Yes except that I'm afraid the diff isn't as clear as a pull request (at least on the web).

**Comment by riobard** [comment]
The commits in this repo are already not very clear. And the fact that we have HTML build results mixed with Markdown sources makes the diff almost useless. So I guess we're not losing anything.

The wiki repo at least only contains source changes.

**Comment by Mygod** [comment]
We can simply ignore the HTML diff.
