### ISSUE TITLE
SHA1 collision

### ISSUE THREAD

**Issue by riobard** [shadowsocks/shadowsocks-org#53]
Google has accomplished [practical SHA1 collision attack](https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html) using 110 GPU-years (cost around $110,000 as of Feb 2017). 

Currently we use SHA1 with HKDF to generate per-session key for AEAD ciphers. Due to the construction of HKDF using HMAC, SHA1 collision should _not_ compromise our security. 

However, we should not _directly_ use SHA1 from now on. Specifically, if we are to attach message digest along with binary builds to release, we need to use SHA256 or SHA512 instead. SHA1 and MD5 are not acceptable.

This is a reminder just in case.

**Comment by shinku721** [comment]
HMAC does not require Collision Resistance if I am right.

**Comment by Mygod** [comment]
Can we close this "reminder" now?
