### ISSUE TITLE
evaluete RC6 cipher

### ISSUE THREAD

**Issue by zhou0** [shadowsocks/shadowsocks-org#55]
according to this paper at http://www.tmrfindia.org/ijcsa/v11i12.pdf

"The RC5 and RC6 ciphers [RSA Security (2005)] in EAX mode demonstrated the
best overall median (i.e. based on encryption of RMM files of all sizes) performance
on technical platform TP2 (i.e. generic Asus netbook) with both Windows and Linux
OS in both single processor 1Proc and multi processor MProc modes of CPU
operation (Table 3, columns ## 7-10). The second best ciphers on TP2 are TwoFish
and AES-128 ciphers; they demonstrated about 33% (on average) lower performance
with Windows OS, and about 47% with Linux OS in comparison with performance
of RC6 and RC5 ciphers."

RC6 US patent will expire on April 21 2017 which is less than 2 months away. Since RC6 in EAX mode ( one of AEAD modes ) has better performance for netbook than AES, so it is desireable to have RC6 support for nebook laptops.

**Comment by riobard** [comment]
I doubt it. The _last_ thing we want right now is more ciphers. 

There's no obvious benefit brought by RC6, and RC6 has no widespread support in the languages and crypto libs we use.

On low-end devices, the future is clearly chacha20.
