### ISSUE TITLE
Add LiFi as an iOS client to website

### ISSUE THREAD

**Issue by tapir** [shadowsocks/shadowsocks-org#56]
I've tried to install Potatso today but it was not free and MobileShadowSocks require jailbreak. So I ended up installing and testing LiFi. It's very simple shadowsocks VPN enabler for iOS. Works quite OK. https://itunes.apple.com/us/app/lifi-shadowsocks-and-shadowsocksr-vpn-client/id1153372559?mt=8

**Comment by hellofwy** [comment]
Needing to buy or not, this is not the main concern. 

I think it should be open-sourced and allow others to do collaboration with a collaboration friendly license.

**Comment by tapir** [comment]
Ideally yes. The most important thing is accessibility for people though.
LiFi is the most accessible one and it's not mentioned in the website. Just
letting you know. I'm not in any way affiliated with the app.

27 Şubat 2017 Pazartesi tarihinde, hellofwy <notifications@github.com>
yazdı:

**Comment by hellofwy** [comment]
What if added to the site, but latter it changes to a paid app?

**Comment by tapir** [comment]
Then don't. Potatso is neither open source nor free and it's on the
website. I was just letting you guys know that as a shadowsocks user LiFi
is the one that worked for me and other people might find it useful.

**Comment by tapir** [comment]
I stand corrected potatso is open source.

**Comment by hellofwy** [comment]
Potatso was open source, but now it is not. The author of Potatso said he is working on new versions which will not open-sourced any more.
