### ISSUE TITLE
Reduce chunk length overhead in AEAD

### ISSUE THREAD

**Issue by riobard** [shadowsocks/shadowsocks-org#57]
I just read a [blog post](http://blog.djm.net.au/2013/11/chacha20-and-poly1305-in-openssh.html) by OpenSSH developer Damien Miller. The following two paragraphs are particularly interesting:

> Both AES-GCM and the EtM MAC modes have a small downside though: because we no longer desire to decrypt the packet as we go, the packet length must be transmitted in plaintext. This unfortunately makes some forms of traffic analysis easier as the attacker can just read the packet lengths directly. OpenSSH takes some countermeasures to obscure the lengths of obvious secrets like passwords used for login or typed into an active session, but I haven't felt entirely comfortable with the protocol revealing the length of every packet sent on the wire.

> The new chacha20-poly1305@openssh.com avoids this though. In addition to providing authenticated encryption with integrity-checking performed before unwrapping encrypted data, this mode uses a second stream cipher instance to separately encrypt the packet lengths to obscure them from eavesdroppers. An active attacker can still play games by fiddling with the packet lengths, but doing so will reveal nothing about the packet payloads themselves - they can make the receiving end read a smaller or larger packet than intended, but the MAC will be checked (and the check will fail) before anything is decrypted or used. Fortunately ChaCha20 is very fast and has quite small keys, so maintaining a separate instance is very cheap.

The blog post points to the [chacha20-poly1305@openssh.com](http://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/usr.bin/ssh/PROTOCOL.chacha20poly1305?rev=1.3&content-type=text/plain) cipher spec with details about handling the packet length:

> When receiving a packet, the length must be decrypted first. When 4 bytes of ciphertext length have been received, they may be decrypted using the K_1 key, a nonce consisting of the packet sequence number encoded as a uint64 under the usual SSH wire encoding and a zero block counter to obtain the plaintext length.

Currently we do double AEAD encryptions per chunk: one for the payload length, and one for the payload itself. The first AEAD encryption is to hide the payload length to get a uniform random stream output, at the cost of one tag overhead (16 bytes). 

The OpenSSH approach quoted above does not have the extra overhead, but it requires an extra stream cipher. For chacha20-poly1305 they can just reuse the same chacha20 cipher. For AES-GCM there's no obvious choice so they do not attempt to hide packet length, and reveal it to adversaries. 

I think their construction is interesting and worth study.

**Comment by wongsyrone** [comment]
![333412b786c353dc5a761aa7ed3bf75b_b](https://cloud.githubusercontent.com/assets/5462232/23494627/de75c9ec-ff4e-11e6-9be2-49f99e450fc1.jpg)
吼啊

**Comment by shinku721** [comment]
I have seen similar construction in obfs4, although obfs4 uses a strange (maybe invented by itself) stream cipher.
Maybe we can drop the length tag, ignore the authenticate error of the length field, and include the length as Associated Data in payload part. However I'm not sure whether the encryption library allows us to do this.

**Comment by shinku721** [comment]
And as the protocol is frequently modified I think we must mark the stability on website.

**Comment by riobard** [comment]
> Maybe we can drop the length tag, ignoring the authenticate error of the length field, and include the length as Associated Data in payload part. However I'm not sure whether the encryption library allows us to do this.

It won't work. By definition AEAD ciphers will refuse to decrypt if authentication fails so as to avoid providing a decryption oracle to attackers.

**Comment by riobard** [comment]
I think the question is a) whether 16 bytes overhead per chunk is acceptable and if not b) should we adopt similar design like the one used in OpenSSH.

**Comment by madeye** [comment]
a) 16 bytes overhead means 16 / 1492 (typical chunk size if MSS = 1492) ~= 1% bandwidth loss. I doubt the overhead is even notable in the real world.
b) The approach of OpenSSH doesn't look good to me, especially the two separate ciphers.
c) Since SIP004 is already finalized, I prefer to not changing AEAD ciphers, unless there is any security concern.

I suggest to do more research about any new AEAD cipher that would solve the chunk length issue internally.

**Comment by riobard** [comment]
I agree. The OpenSSH design leaves the possibility open that adversaries can control the obfuscated length field. Even though it does not pose any security threat because the payload is still AEAD-protected, I wonder if it exposes timing characteristics that might enable attacks similar to @breakwa11's to identify the protocol we use.
