### ISSUE TITLE
Unifying chacha20-poly1305 ciphers

### ISSUE THREAD

**Issue by riobard** [shadowsocks/shadowsocks-org#58]
Historically we have had three variants of chacha20-poly1305 AEAD ciphers:

1. The original `chacha20-poly1305` with 64-bit nonce.
2. The IETF-variant `chacha20-ietf-poly1305` with 96-bit nonce.
3. The extended `xchacha20-poly1305` with 192-bit nonce.

Before SIP007, the original variant was ditched due to high probability of nonce reuse. SIP007 introduced per-session key and counting nonce, effectively making the three variants equivalent in strength of security and the size of nonce irrelevant. 

I propose we just use a single cipher called `chacha20-poly1305` to refer to the IETF-variant since the original and the extended variants are rarely used in other places anyway. This will simplify the AEAD cipher choice and reduce confusion for users.

Reference [ChaCha20 and Poly1305 for IETF Protocols](https://tools.ietf.org/html/rfc7539)

**Comment by hellofwy** [comment]
Simplify is the beginning of confusion.

**Comment by shinku721** [comment]
No. Don't do this. This may be even more confusing.
Deprecating unused ciphers is effective enough.

**Comment by riobard** [comment]
AFAIK `xchacha20-poly1305` was never implemented, and `chacha20-poly1305` was removed anyway. There's only `chacha20-ietf-poly1305` variant available, and it's silly for users to remember the extra `ietf` thing if that's the only one we support. 

OpenSSH didn't call their implementation `chacha20-ietf-poly1305@openssh.com` and TLS didn't call their cipher suite `TLS_CHACHA20_IETF_POLY1305_SHA256`. 

If we want the AEAD cipher to be widely adopted, we should prefer one to make it easier for clients to pick.

**Comment by Mygod** [comment]
I'm afraid renaming cipher is not an option. It solves fewer problems than it causes.

**Comment by riobard** [comment]
Why not? AEAD ciphers are only supported in three implementations so far. It's much better to stick with one name before more implementations make the same mistake.

**Comment by Mygod** [comment]
Because I'm afraid it's already too late. :sweat_smile:

**Comment by riobard** [comment]
It's less than one month old. There's still plenty of time to fix it ^_^

**Comment by Mygod** [comment]
Nah. Methinks the current approach is better even if you proposed this before ss-libev implements it. We need consistency between non-AEAD variants `chacha20-ietf` and `chacha20`.

**Comment by riobard** [comment]
The consistency only makes sense if we have both `chacha20-ietf-poly1305` and `chacha20-poly1305`. We have just one, and it's the default one. It should have shorter, consistent name with every other use case e.g. OpenSSH and TLS.

**Comment by Mygod** [comment]
Having internal consistency is more important than being consistent with some other libraries.

**Comment by riobard** [comment]
BTW `chacha20` stream cipher is deprecated due to its 64-bit IV.

**Comment by Mygod** [comment]
Deprecated isn't the same as removed. And even if it's removed it's still more confusing to rename it. It's generally a bad idea.

**Comment by riobard** [comment]
So past mistakes stick forever? I bet not.

**Comment by riobard** [comment]
This is the chance to fix legacy issues.

**Comment by Mygod** [comment]
> So past mistakes stick forever? I bet not.

Unfortunately this is very true, at least in this field.

**Comment by riobard** [comment]
I beg to differ. TLS 1.3 draft used to use 64-bit nonce variant AEAD_CHACHA20_POLY1305. They changed it to 64-bit nonce (effectively the IETF-variant) while keeping the name. In fact, AEAD_CHACHA20_POLY1305 is now formally defined in RFC 7539. We should follow the standard.

**Comment by Mygod** [comment]
> TLS 1.3 **draft**

**Comment by riobard** [comment]
>  AEAD_CHACHA20_POLY1305 is now formally defined in RFC 7539. We should follow the __standard__.

**Comment by madeye** [comment]
Maybe add chacha20-poly1305 as alias to chacha20-ietf-poly1305 in shadowsocks? Then, everyone would be happy...

**Comment by riobard** [comment]
@madeye I was thinking _exactly_ the same! 👍

**Comment by Mygod** [comment]
@riobard That doesn't prove anything. A draft is by definition subject to change. And this is different.

@madeye Probably not. Now you have a compatibility problem which is much worse.

**Comment by Mygod** [comment]
You can't just finalize a draft and change your mind. Absolutely no.

**Comment by riobard** [comment]
I don't see a tag anywhere saying this is "finalized".

**Comment by Mygod** [comment]
Even if nobody has said the word "finalized" there are also quite a few synonyms:

* #30 is closed.
* shadowsocks-libev released v3.0.3 as a stable version without any signs like :construction: or AEAD subject to change. (see [this warning](https://github.com/shadowsocks/shadowsocks-android/blob/684698c/plugin/README.md#developers-guide) for example)
* Neither can anyone find stuff like that in [spec](https://shadowsocks.org/en/spec/AEAD-Ciphers.html).
* Having a spec page also implies it's finalized.

**Comment by madeye** [comment]
Hmm, confusion is the biggest concern, especially for our normal users. I suggest at least keeping the name chacha20-ieft-poly1305 in shadowsocks, which won't break anyone's config files.

**Comment by Mygod** [comment]
If you really want to make this change, start putting construction signs everywhere mentioning AEAD and I won't object this any more.

**Comment by riobard** [comment]
I'd like to know which implementation has both `chacha20-poly1305` and `chacha20-ietf-poly1305`, and who actually deploys the former in practice?

**Comment by Mygod** [comment]
Fine whatever. I'm done wasting my time discussing naming issues.

**Comment by hellofwy** [comment]
Just follow the name used in crypto libraries, as Shadowsocks doesn't provide this.

**Comment by riobard** [comment]
@hellofwy Not all implementations use the the same crypto libs. It's better to stick to RFC.

**Comment by hellofwy** [comment]
Does RFC 7539 is a well implemented RFC?

If standardize this cipher name, maybe should standardize  all the cipher names as well, and provide a table which lists corresponding names in crypto libraries.

And provide infos about from which version begin supporting all the new names.

**Comment by riobard** [comment]
There are two relevant RFCs:

- [RFC 5116](https://tools.ietf.org/html/rfc5116) specifies general AEAD interfaces and AES-128/192/256-GCM in particular
- [RFC 7539](https://tools.ietf.org/html/rfc7539) specifies Chacha20-Poly1305

Other ciphers are not well defined.

**Comment by riobard** [comment]
Ok. If renaming old cipher is important, may I propose that we adopt the IANA AEAD registry? http://www.iana.org/assignments/aead-parameters/aead-parameters.xhtml

**Comment by riobard** [comment]
Just use the following alias:

1. `chacha20-ietf-poly1305` to `AEAD_CHACHA20_POLY1305`
2. 'aes-128-gcm` to `AEAD_AES_128_GCM`
3. 'aes-192-gcm` to `AEAD_AES_192_GCM`
4. 'aes-256-gcm` to `AEAD_AES_256_GCM`

**Comment by riobard** [comment]
At least each one in that list has a well-defined specification.

**Comment by riobard** [comment]
@Mygod This does not rename old ciphers. I guess you might be OK with it?

**Comment by riobard** [comment]
Best thing with the IANA registry is that they assigned a unique numeric ID for each cipher suite. Should be easier to deal with in code.

**Comment by Mygod** [comment]
It's kinda better. But I honestly don't care any more.

**Comment by riobard** [comment]
Closing now. New proposal at #61.
