### ISSUE TITLE
Track AEAD support on website

### ISSUE THREAD

**Issue by henrypijames** [shadowsocks/shadowsocks-org#59]
Now the AEAD protocol has been finalized, most SS implementations will hopefully support it. However, it is very difficult for the regular user to know (or even track) which implementation has AEAD support, since most implementations do not provide clear information about it on their website (be it Github project page, AppStore page, or Google Play page).

Therefore, it would be good and useful to track the AEAD support status of different SS implementations on the `shadowsocks.org` website. And while we're at it, plugin support as well. This can be done in two ways (either or both):

1. On the `download/clients` and `download/servers` pages, add footnotes to the name of every listed software that support AEAD and/or plugins, e. g. **A** for AEAD and **P** for plugin.

2. On the `spec/aead` and `spec/plugin` pages, add a section at the bottom to list those software that support the respective protocol.

**Comment by henrypijames** [comment]
I see the original SS project had a [Feature Comparison](https://github.com/shadowsocks/shadowsocks/wiki/Feature-Comparison-across-Different-Versions) page on its Wiki. Maybe we can do something like that.

**Comment by riobard** [comment]
I think this is a duplicate of #22  ?

**Comment by henrypijames** [comment]
Why, yes.
