### ISSUE TITLE
Follow IANA registry for AEAD ciphers

### ISSUE THREAD

**Issue by riobard** [shadowsocks/shadowsocks-org#61]
IANA has a dedicated AEAD registry defining numeric ID, common name, and reference specification for AEAD ciphers. Compliant Shadowsocks implementations should follow the naming scheme http://www.iana.org/assignments/aead-parameters/aead-parameters.xhtml

In particular, AEAD_CHACHA20_POLY1305 must be implemented as a common cipher. Implementations intending to run on devices with hardware AES acceleration should also implement AEAD_AES_128_GCM, AEAD_AES_192_GCM, and AEAD_AES_256_GCM.

For backward compatibility, alias 
- `chacha20-ietf-poly1305` to `AEAD_CHACHA20_POLY1305`;
- `aes-128-gcm` to `AEAD_AES_128_GCM`;
- `aes-192-gcm` to `AEAD_AES_192_GCM`;
- `aes-256-gcm` to `AEAD_AES_256_GCM`.

**Comment by madeye** [comment]
LGTM. Let's keep the alias to ensure backward compatibility.

**Comment by madeye** [comment]
Updated via https://github.com/shadowsocks/shadowsocks-org/commit/3e7a7075ddbd2b74e1fdbcb5beb7ee6fda550161
