### ISSUE TITLE
Question about the UDP module for ss

### ISSUE THREAD

**Issue by arthurkiller** [shadowsocks/shadowsocks-org#67]
UDP is a packet oriented protocol. So how do we implement shadowsocks based on udp?

## 1) Act like a udp turnel
__client__   ---udp---   __ss-local__   ---udp[ss]---   __ss-remote__   ---udp--- __dest__

client send the packet to the ss-local and suggest the ss-local will forward  the packet from the port  to the destination address follow the `rules`

port1<-->dest1 , port2<-->dest2

## 2) Act like the TCP ss server
__client__   ---socks5---   __ss-local__   ---udp[ss]---   __ss-remote__   ---udp--- __dest__

client connect to the ss-local and give the request, then ss-local forward the request to the ss-remote, ss-remote send the request to the destination which defined in the socks request.

**Comment by arthurkiller** [comment]
I have no idea about if the socks5 can suit the udp? Or udp just should use as turnel module? Or both plan are ok???

**Comment by arthurkiller** [comment]
And another question is how could I join the ss develope team?

**Comment by madeye** [comment]
> I have no idea about if the socks5 can suit the udp? Or udp just should use as turnel module? Or both plan are ok???

Section UDP ASSOCIATE X'03', https://www.ietf.org/rfc/rfc1928.txt

> And another question is how could I join the ss developer team?

Just start from figuring out how shadowsocks works...

**Comment by arthurkiller** [comment]
@madeye  I have reconstruct the shadowsocks-go, but seems this project is abandoned?

**Comment by arthurkiller** [comment]
Cause the go-shadowsocks2 only support the turnel module for udp

**Comment by madeye** [comment]
> Cause the go-shadowsocks2 only support the turnel module for udp

Then my suggestion is you can start from adding UDP ASSOCIATE to go-shadowsocsk2 first, or adding AEAD cipher to shadowsocks-go.

**Comment by arthurkiller** [comment]
@madeye  I have done the AEAD on my local branch for ss-go, but still need to test & bug fixing. 
UDP module is also TBD. Thx a lot ,dude

**Comment by arthurkiller** [comment]
#79

**Comment by wansheg** [comment]
compare with xl2tp ,  shadowsocks is  slower than  "xl2tp"  for single connection . 
recently, I need remote work at home , and connect to company's VPN server in USA from china . 
firstly, I setup  "l2tp" client and "shadowsocks" client  in my openwrt router , and connect  to VPS in CN2( chinese next generation carrier network ) in USA.   
in my local machine , I setup cisco any-connect  VPN to connect  VPN server in Los Angles , 
with using l2tp and relay on   VPS in CN2 net ,  the average speed is  10Mbps 

without using l2tp and relay on VPS in CN2 net , the average speed no more than 1Mbps 

with using "shadowsocks" and relay on VPS in CN2 net , the average  speed is  5Mbps 

I will change  code to setup UPD connect between shadowcosks client and server 
UDP is fast than TCP for single connection
