### ISSUE TITLE
现在的URL支持的标准变成什么样了？

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/shadowsocks-org#68]
原始标准应该是 ss://bf-cfb:test@192.168.100.1:8888

我记得加入OTA功能之后，语法有扩展。现在去除OTA,又加入插件功能的话，

看到有些客户端更新了，比如支持多服务器的URL，谁能给出一个标准，统一的URL？

**Comment by sorz** [comment]
https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html
