### ISSUE TITLE
In AEAD mode, does the first chunk always contain only the address field?

### ISSUE THREAD

**Issue by DarienRaymond** [shadowsocks/shadowsocks-org#69]
Just want to clarify the expected behavior, as the official doc doesn't not define this clearly.

In AEAD mode, TCP request is in the following form:
[1. nonce][2. encrypted payload length][3. length tag][4. encrypted payload][5. payload tag][6. repeat....]

Does part 4 contains the address only? and the whole address field must be in part 4?

Example:
Address: 8.8.8.8:80
Serialized in bytes: 1 8 8 8 8 0 80
TCP request: [nonce][7 (length)][tag][1, 8, 8, 8, 8, 0, 80][tag]

Alternative form:
1. [nonce][10 (length)][tag][1, 8, 8, 8, 8, 0, 80, payload(3 bytes)][tag]
1. [nonce][3 (length)][tag][1, 8, 8][tag][4][tag][8, 8, 0, 80][tag]

Are alternative forms allowed?

**Comment by madeye** [comment]
There is no constraint for first chunk's payload.  Part of address, whole address, and whole address plus underlying TCP payload are all legal.

**Comment by DarienRaymond** [comment]
Thanks for the clarification.
