### ISSUE TITLE
A REQUEST about updating Shadowsocks.

### ISSUE THREAD

**Issue by SkyFuInMC** [shadowsocks/shadowsocks-org#70]
Recently an anonymous person announced that Beijing University of Posts and Telecommunication has developed a method that can detect Shadowsocks connections and try to interrupt Shadowsocks connections. He also announced that the method will be apllied in February, 2018. A picture might be here. Hope you try to update your working method and fix the problem! Thank you very much!!! 
![38998ff68f3177e0](https://user-images.githubusercontent.com/15964383/28236726-42d8c110-68f3-11e7-885e-04fff7af2818.jpg)
Another link should be below:

**Comment by wongsyrone** [comment]
好消息

https://www.mitbbs.com/article_t/Military/48410843.html

**Comment by shinku721** [comment]
So please provide more information on this attack. Or I'll think it's just slowing or blocking any unrecognizable traffic.

**Comment by wongsyrone** [comment]
From ShadowsocksR news, just for your information:

很多人不相信SS能被精准识别的事实，那我再公布一个东西，iKuai 的路由器固件可以精确针对SS流控，这个模块于2016年下半年实现的，不过到至今没有改动，即对AEAD没有效果，但你可以使用那个来测试是否精确拦截SS流量，既然有其它人已经做成成品，那我就没必要自己浪费时间写一个来证明了，但这并不代表AEAD加密的SS不能识别
