### ISSUE TITLE
One more implementation of shadowsocks in go

### ISSUE THREAD

**Issue by shinku721** [shadowsocks/shadowsocks-org#71]
Well, I know we have a bunch of implementations of shadowsocks in go... But I still choose to implement another one.
My code here: https://github.com/shinku721/shadowsocks-goo
I wish it will be a good one, with clear design, low resource requirement, rich features and full documentation. Currently it supports socks4a and HTTP proxy besides socks5 (HTTP needs more test). I need your help on development and testing.
Please feel free to review the code, make issues and PRs.

**Comment by madeye** [comment]
It looks you implemented the HTTP proxy feature from scratch? Maybe there are already libraries for this?

**Comment by shinku721** [comment]
Yes, from scratch.
AFAIK there is no HTTP proxy library that meets the need. I do not need a full HTTP proxy but a library that can parse HTTP headers, handle bodies of constant length as well as chunked ones, and tell me how to make the requests. The incoming requests are from the (maybe) multiplexed port instead of an independent one, while the HTTP proxy backend makes requests in shadowsocks connections.
Also I hope to use least third-party libraries (and even internal libraries) to make it more lightweight and controllable.
I know there is net/http... However, first it's heavy. Second, it does not do so much about proxying, so I still have to handle header stuffs... And third it requires go's internal stream interface which implies extra buffers.
If anyone knows the right library or has any advice (for example, ways to make it elegantly with net/http), please let me know it! (Or just make PRs implementing the interface)

**Comment by madeye** [comment]
Assuming we only support HTTP connect, this project may be useful: https://github.com/getlantern/lantern/tree/devel/src/github.com/getlantern/http-proxy

**Comment by shinku721** [comment]
@madeye , thanks for recommendation.
However, the project is slightly different in detail... What I have implemented covers CONNECT and other methods (GET/POST/...), so it can proxy any connections. The mentioned project also uses net/http.
I hope not to include net/http... Because this makes the binary increase 4.3M in size before strip and 2.9M even after strip.
