### ISSUE TITLE
Rust port of shadowsocks

### ISSUE THREAD

**Issue by zonyitoo** [shadowsocks/shadowsocks-org#72]
`shadowsocks-rust` is a port of shadowsocks in Rust.

https://github.com/zonyitoo/shadowsocks-rust

Is it possible to add this into shadowsocks' organization? Ref https://github.com/zonyitoo/shadowsocks-rust/issues/53

**Comment by wongsyrone** [comment]
https://docs.rs/rand/0.3.14/rand/#cryptographic-security

另外我竟然看到了Argon2？那个是之前讨论的产物了

**Comment by zonyitoo** [comment]
什么的讨论？求个Link

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-org/wiki/AEAD-Ciphers

你看这个就行了，之前讨论的在SIP004里面

**Comment by zonyitoo** [comment]
没有理解。我看过这里的文档，也是从讨论里得知希望使用Argon2来做key derive。是现在已经决定不改key derive了么？
在我这里是一个optional选项，默认都是不打开的。

**Comment by wongsyrone** [comment]
key derivation 现在是HKDF

另外随机数生成属于加密里的重要而又易被忽略的环节，应使用内核提供的，rust文档说的也很清楚

https://www.zhihu.com/question/21826283

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues/30#issuecomment-275903760
我是根据madeye说的这个来决定加入Argon2到代码里的。后面的讨论我没有跟。

HKDF的难道不是说的这个SessionKey??
https://github.com/zonyitoo/shadowsocks-rust/blob/master/src/crypto/aead.rs#L59-L99

我一段时间没有看社区的讨论了，可能比较Out了

**Comment by wongsyrone** [comment]
感觉你可以去掉Argon2的部分了，其他的只是粗略一看，SessionKey那部分看起来没啥问题

**Comment by zonyitoo** [comment]
在每次的Cipher创建时，都会调用`make_skey`来进行key derivation。 https://github.com/zonyitoo/shadowsocks-rust/blob/master/src/crypto/ring.rs#L42

是根据我之前clone的`shadowsocks-libev`的实现来做的。

我刚粗略看了一下，好像新的实现并不需要在前面先做一层处理？

**Comment by wongsyrone** [comment]
这个你可以和其他实现互跑看看。key derivation是每条tcp做一次的，一个salt对应一次

**Comment by zonyitoo** [comment]
这个是没有问题的。每条连接都肯定会做一次`make_skey`，也会调用一次`gen_salt`。问题在于在应用启动时，对`password`的处理，我之前看是会先用之前的MD5或新的Argon2处理一次，再每次都用这个结果传入`make_skey`。这个我之后再具体测试一下。

`salt`的生成问题，我稍候commit一个使用`OsRng`的版本。之前确实没有留意这一点。

**Comment by zonyitoo** [comment]
Rng问题已Fixed.

关于AEAD key derivation的问题，我翻查了`shadowsocks-libev`的代码

1. https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/aead.c#L691-L692 此处依然需要调用 `crypto_derive_key`
2. https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/crypto.c#L199 似乎确实已经去除了[Argon2的代码](https://github.com/shadowsocks/shadowsocks-libev/commit/e18f71b03fb54a0d34b6aa41f8966620722c4c56)

**Comment by zonyitoo** [comment]
@wongsyrone 两个问题都已Fixed.

**Comment by zonyitoo** [comment]
@wongsyrone Is it Ok? 
cc @madeye

**Comment by madeye** [comment]
Have you tested with the latest shadowsocks-libev or go-shadowsocks2?

**Comment by madeye** [comment]
I've sent you an invitation. You can then fork the project or transfer it to the org.

**Comment by zonyitoo** [comment]
I have already tested with `shadowsocks-libev`.
