### ISSUE TITLE
Question about the AEAD documents

### ISSUE THREAD

**Issue by arthurkiller** [shadowsocks/shadowsocks-org#75]
Hey dude, recently I get start with the AEAD cipher document. But something in documents makes me confused.

It's in chapter AEAD, section TCP , here we get this: [_here_](https://shadowsocks.org/en/spec/AEAD-Ciphers.html#TCP)

> [encrypted payload length][length tag][encrypted payload][payload tag]

In my view. We just get the message length and message itself both encrypted and authenticated. 

Workflow should like this:

__[ length of message ][ raw message ]  == AEAD ==> [ encrypted length + authentication ][ encrypted message + authentication ]__

So doucument could get more clearly with word like this:

> [ encrypted payload length ][ length authentication][ encrypted payload ][ payload authentication ]

I was confused about the word _tag_ ,and wonder what it is! Cause the _tag_ has appeared in the document before. But I think both tags are equal to the _Message Authentication Code (MAC)_ , so word `authentication` can become more clearly than tag. 

> AE_encrypt(key, nonce, message) => (ciphertext, tag)
> AE_decrypt(key, nonce, ciphertext, tag) => message

Thx alot

**Comment by arthurkiller** [comment]
@madeye If I get something misunderstand , let me know. Thx

**Comment by Noisyfox** [comment]
The word **tag** is used more often when it comes to Authenticated Encryption since the name of that MAC is called **authentication tag**

**Comment by arthurkiller** [comment]
@Noisyfox  Thx for jump in.

I just get confused by the word tag without authentication, if this is a common abbreviation as `tag` I will have no doubt with this.
