### ISSUE TITLE
Confused about socks5 protocol and it's implement in ss

### ISSUE THREAD

**Issue by bosskwei** [shadowsocks/shadowsocks-org#77]
socks5 协议规范的第六条是 server 返回给 client 的状态
例如 client 请求通过 server 中继 connect 到 'google.com:443'，server 执行操作以后返回給 client 这样一个答复：
```
+----+-----+-------+------+----------+----------+
|VER | REP |  RSV  | ATYP | BND.ADDR | BND.PORT |
+----+-----+-------+------+----------+----------+
| 1  |  1  | '00'  |  1   | Variable |    2     |
+----+-----+-------+------+----------+----------+
```
请问这里的 `BND.ADDR` 和 `BND.PORT` 究竟有何作用？
在此处是否可以，server 不建立连接而是直接返回 success，等到 第一次 recv(client) 有数据以后再 connect 和 中继？

**Comment by ccsexyz** [comment]
1.基本上没用，只有 udp 模式下向 socks5 客户端告知用于中继的 udp 套接字地址用到了。
2.可以。

https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/local.c#L492

**Comment by bosskwei** [comment]
@ccsexyz 谢谢，了解了
另外再请教一点，**假设** sslocal 和 google.com 交互需要 3 个 socket，于是 sslocal 和 server 之间有 3 个 socket，同时 server 和 google.com 之间也是 3 个 socket，socket 一一对应只负责转发自己那个的数据。

**或者说**假如我打开了 20 个 youtube 建立长时间连接的 socket 共 100 个，那么
1. 从我的浏览器到 sslocal 之间是 100 个 socket
2. 从 sslocal 到 ssserver 之间是 100 个 socket
3. 从 ssserver 到 youtube.com 之间也是 100 个 socket
是这样对吗？

**Comment by ccsexyz** [comment]
@bosskwei 
1.关于连接数的理解是正确的。
2.这里的短数据包是 socks5client 和 sslocal 握手的时候发送的，不用担心会被发现。
可以读读 https://github.com/shadowsocks/shadowsocks-go 这个项目的代码，对理解 shadowsocks 的工作流程可能会有帮助

**Comment by bosskwei** [comment]
@ccsexyz 谢谢，我仔细看了一天代码终于理解了，原来是 sslocal 把 socks5 的协议转换成 ss 协议再发送给 ssserver 的。我最近在试着用 py 重新实现一遍 ss，py 版的 ss 太乱了。

    +--------------+---------------+--------------+------------+
    |  *DataLen*   |  DataLen_TAG  |    *Data*    |  Data_TAG  |
    +--------------+---------------+--------------+------------+
    |      2       |     Fixed     |   Variable   |   Fixed    |
    +--------------+---------------+--------------+------------+

然后我又遇到几个新问题，再来打扰下各位求指教。
AEAD 加密方法下，对 TCP 包做了分段(Chunk )，然后把包长写到了加密后的协议头 DataLen 中然后还有个固定的 `DataLen_TAG`，我真的不是很理解为啥要这样做，主要是这几个问题
1. 为什么要把 TCP 包分段？ 分段合并数据这种事情难道不应该是 TCP 协议栈来完成的么？
2. `DataLen_TAG` 是个固定值，很容易被提取出特征
3. `DataLen` 是个与当前数据包特征相关的变量，因此甚至不用什么复杂的机器学习，只要计算 前两个字节 与 整个数据包特征 的协方差，再配合其他一些 socket 层面的特征，应该可以轻易识别出 ss 流量？我有仔细看过 SIP004，但是对这种协议的设计思想不甚了解，还请指教，谢谢

**Comment by wongsyrone** [comment]
https://stackoverflow.com/questions/1595163/is-authentication-required-recommended-with-a-stream-cipher

因为要验证数据，所以一定会分段的，一整条怎么验证XD，核心思想是分段验证之后传输，目的是为了防止针对修改密文的主动探测，可以去翻各种issue

AEAD协议其实很类似于TLS，只不过不会明文发证书

安全和速度之间一定会有取舍的，看你更看重哪一个。

**Comment by wongsyrone** [comment]
其实你可以这么想，如果是大同世界，加密根本没有存在的必要性了。
为了达到其他目的，一定会加入各种元信息来描述数据，这些就变成了overhead

**Comment by bosskwei** [comment]
谢谢，我再想想 @wongsyrone
