### ISSUE TITLE
A new implementation of shadowsocks in Python

### ISSUE THREAD

**Issue by bosskwei** [shadowsocks/shadowsocks-org#78]
Hi guys,
There's a new implemention of shadowsocks, [https://github.com/bosskwei/shadowsocks-naive](https://github.com/bosskwei/shadowsocks-naive)

The reason for developing this project is that current ss-python is difficult to understand, because it mix up client and server in `tcprelay.py` with disordered `if...else` and ota.

Python program should be a prototype of a project, for esay reading, learning and expanding. So the ss-naive aimed to build a light weight and clear designed branch, just like it's name, make everything simple and naive.

Project based on python-asyncio (a standard event loop library since PY34) and cryptography (openssl wrapper), and only support PY35 or later.

TCP and UDP protocol are tested days with stream cipher (test with ss-windows client, firefox and BitTorrent), aead cipher will finish as soon as possible.

**Comment by pexcn** [comment]
naive?

**Comment by bosskwei** [comment]
@pexcn Yes, very naive

**Comment by pexcn** [comment]
Why not call it `simple`? 😋

**Comment by riobard** [comment]
Too simple, sometimes naive? 😄

Anyway, if you feel ss-python is hard to understand, it's better to submit pull requests to make it easier to understand. 

It's fine to implement your own version for education purpose, but in general we do not adopt such effort.

**Comment by bosskwei** [comment]
哎哈哈，那就算了，其实这个也就是我自己写着玩的，py 就图个好玩嘛，用那个 asyncio 库写出来确实可读性不错，我自己本地用 hfs 测速度也能跑到 30M/s

**Comment by pexcn** [comment]
:yum::yum::yum:
