### ISSUE TITLE
Security issue on the AEAD UDP ciphers?

### ISSUE THREAD

**Issue by zasdfgbnm** [shadowsocks/shadowsocks-org#82]
In [this page](https://shadowsocks.org/en/spec/AEAD-Ciphers.html), I see that for AEAD UDP ciphers, 
> Each UDP packet is encrypted/decrypted independently, using the derived subkey and a nonce with all zero bytes.

Is it safe to use all zero nonce for every packet? Shouldn't nonce be something unique for each packet?

A bad idea to generate a unique nonce might be to use a counter as nonce and append that counter after encrypted data. But this increasing sequence at the end of message will become a character that can be used to detect protocol.

A better way might be to use a stream cipher to encrypt that counter and append the IV for the stream cipher. This way, the packet will still look randomish, and we have a unique nonce for each packet.

**Comment by madeye** [comment]
Read SIP007 https://github.com/shadowsocks/shadowsocks-org/issues/42 for more details.

**Comment by zasdfgbnm** [comment]
@madeye Thanks a lot for the pointer :)

I see the following thing [in the discussion](https://github.com/shadowsocks/shadowsocks-org/issues/42#issuecomment-279144793):
> I applied similar treatment to derive a new subkey for each UDP packet with nonce setting to all zero.

I'm not sure if I understand correctly. According to my understanding, the master key will be something that user specify and might not change for years. But for each session, the key actually used is the subkey, which changes per session. This provide M random bits.

In addition, for TCP, there is a counter used as nonce, which provide additional N random bits. Therefore in total, there are M+N random bits.

But for UDP, the nonce is always 0, for every packet, which means, in total, there will be only M random bits, making it less secure than TCP. Is this correct?

Would there be additional issues in reusing nonce? I find [something](https://crypto.stackexchange.com/questions/39550/repeated-nonce-in-ctr-mode), but I'm not sure if it is related:
>My understanding is that, in CTR mode, the NONCE must be unique because, if a NONCE is reused, multiple plaintexts will be XORed with the same value and this gives an attacker leverage to decrypt the data.

**Comment by madeye** [comment]
1. A UDP packet equals a TCP stream with one chunk.
2. The nonce of the first chunk of a TCP stream equals 0.
3. There is a salt for each UDP packet, which works as nonce of HKDF to generate sub-key.

**Comment by madeye** [comment]
> In addition, for TCP, there is a counter used as nonce, which provide additional N random bits. Therefore in total, there are M+N random bits.

Nope, Nonce is not generated randomly. Only M "random bits" for both TCP and UDP.

To ensure enough security, the minimum key length of shadowsocks' AEAD ciphers is 128 bit.

**Comment by zasdfgbnm** [comment]
@madeye Oh, yes this looks good to me now. There is a salt for each UDP packet, therefore, they are using different subkeys, then there is no need to use a different nonce. Thanks for your time for clarification. Closing.
