### ISSUE TITLE
关于开源协议和代码复用的问题

### ISSUE THREAD

**Issue by Mr-indescribable** [shadowsocks/shadowsocks-org#83]
各位上游维护者们，你们好。

抱歉，我的英语不够流利，由于担心造成误解所以使用汉语编写这个 issue。

我最近 DIY 了一个代理程序，TCP 部分从 shadowsocks 的 TCPRelayHandler 中复制了一些函数，并做了一些改动以用于自己的项目。目前我对于 Apache2.0 开源协议的处理方法是在这几个函数中写下 shadowsocks 中的 Copyright 和 License 信息并注明我对代码做过改动。

由于我接触开源的时间比较短，有许多不明白的地方，我阅读了 Apache2.0 开源协议，我没有在其中找到关于我这类行为内容。由于联系上 clowwindy 本人非常困难，所以在此请教。

项目链接以及复制的函数：[ir](https://github.com/Mr-indescribable/ir#copyright--license)

问题1：

* 我这样的做法是否违反 Apache2.0 开源协议? 或者说，是否可以得到当前维护者的允许？

-------------------------------

另外，我的项目中有一个 tcp_pre_connect 分支，我准备将其合并到 master 上，其中 TCP 部分对于这几个复制自 shadowsocks 的函数做了大量改动。

复制自shadowsocks的函数的代码链接: 

* 此分支中 _update_stream 函数已经删除
* [TCPHandler._write_to_sock](https://github.com/Mr-indescribable/ir/blob/tcp_pre_connect/ir/handler.py#L121)
* [TCPHandler._on_local_read](https://github.com/Mr-indescribable/ir/blob/tcp_pre_connect/ir/handler.py#L200)
* [TCPHandler._on_remote_write](https://github.com/Mr-indescribable/ir/blob/tcp_pre_connect/ir/handler.py#L234)
* [TCPHandler._on_remote_read](https://github.com/Mr-indescribable/ir/blob/tcp_pre_connect/ir/handler.py#L245)
* [TCPHandler._on_local_write](https://github.com/Mr-indescribable/ir/blob/tcp_pre_connect/ir/handler.py#L273)

问题2：

* 在存在大量改动的情况下，我是否可以不保留原有的 Copyright 和 License 信息？

**Comment by madeye** [comment]
> 我这样的做法是否违反 Apache2.0 开源协议? 或者说，是否可以得到当前维护者的允许？

You'd provide the license of shadowsocks-python when publishing your software. If so, it won't violate the license.

> 在存在大量改动的情况下，我是否可以不保留原有的 Copyright 和 License 信息？

Yes, you still need to keep the license, as your software is derived from shadowsocks-python.

**Comment by Mr-indescribable** [comment]
@madeye 

Understood. Thanks for your reply. 😆
