### ISSUE TITLE
Shadowsocks-libev server no reply

### ISSUE THREAD

**Issue by no1be4me** [shadowsocks/shadowsocks-org#84]
I cannot get any reply from one server sitting in another country. Shadowsocks-libev 3.0.8+DS-2~bpo8+1is what is on my Debian 8 server.
My clients are Shadowsocks version 0.3.2(REV3) by Linus Yang on JB iPhone from cydia & Windows 4.0.6 client.
 I logged into my server from another country and can see the the request accepted and the server establish connection with the client and process the domain I am trying to reach but there is not connection back to the client. Windows nor iPhone. 
I have Port forwarding for the server on the router that the server is connected to. 
iPtables set on the server to accept connections.
Still no reply from the server to the client.
I have disabling the firewall on the server to test, still cannot get reply on the client from the server, even thought I see the client reached the server.

Really will like help with this. thanks

**Comment by madeye** [comment]
Dup https://github.com/shadowsocks/shadowsocks-libev/issues/1707
