### ISSUE TITLE
Unable to bypass random forest based detection!

### ISSUE THREAD

**Issue by cbwang2016** [shadowsocks/shadowsocks-org#85]
Because of the paper: [The Random Forest based Detection of Shadowsock's Traffic](https://github.com/shadowsocks/shadowsocks-libev/files/1374916/10.1109.IHMSC.2017.132.pdf), more and more servers are getting blocked these days. Is it necessary to fully upgrade the protocol as soon as possible?

**Comment by arthurkiller** [comment]
make sure what actually happened is much more important.

These days, my VPS get blocked. Let me tell what happend:
0\ I have 4 independent port listened on my VPS to take service
1\ First day,  One of them was blocked. But others are reachable. I still can SSH to remote login my host.
2\ Next day , all my port was blocked and 22 port also be blocked. I can not even remote login my host anymore.
3\ My service on AWS got some trouble too these days. And the traffic from Peking to Singapore looks good, but incoming traffic looks just like bull shit! 60% packet got lost. 

So , In my view, there is no evidence shown that there comes any tech way to detect SS trafic. What happened is only CAUSE OF THE COMMING MEETING OF CCP

**Comment by arthurkiller** [comment]
Don't worry, be happy

**Comment by bosskwei** [comment]
There are lots of errors in that paper, here are some examples:
![31440812-cad89be2-aec3-11e7-81d1-06ab0adc6dde](https://user-images.githubusercontent.com/12762888/31441946-61098308-aec7-11e7-9b5f-fb20cb0f3586.png)
![31441021-7c66f1ce-aec4-11e7-8231-9cbc091da2a5](https://user-images.githubusercontent.com/12762888/31441948-61bfcc8a-aec7-11e7-8faa-60891ee6010e.png)
![31440536-e2ea1a72-aec2-11e7-8b28-bec5945f6e7b](https://user-images.githubusercontent.com/12762888/31441950-62b59ee4-aec7-11e7-9ad3-33348ca8edbe.png)

**Comment by arthurkiller** [comment]
LOL

**Comment by zasdfgbnm** [comment]
Is there any evident that shows that your VPS got blocked is due to the method described as in the paper? Maybe they just use unpublished but some more advanced, more accurate method to detect SS.

**Comment by Vywh** [comment]
There is no evidence that GFW use random decision trees to detect shadowsocks traffic.

**Comment by Mygod** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues/81#issuecomment-336019891

**Comment by cbwang2016** [comment]
@Mygod "It's not very realistic for a country scale firewall to record every international packets and do statistical analysis."
They only need to do statistical analysis when training the Random Forest, but not when detecting. It's difficult for you to learn how to walk, but once you've learned, walking is the simplest thing in the world.

**Comment by Mygod** [comment]
@cbwang2016 If you read their paper, you will see that their features are statistical features.

**Comment by Seraphli** [comment]
@Mygod Maybe it's not country-size detection, it's region-based detection. And also the whole detection system can run on every network traffic center. Model in every local network center can be updated by the control center. The control center needs to train and update the model.

**Comment by Mygod** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues/86#issuecomment-336610628
