### ISSUE TITLE
(Hot from the press) Paper from Wang et al. From Cali State Riverside analyses and discusses current strategies of GFW and proposes ways around them. Can we implement any of their suggestions to further improve shadowsocks?

### ISSUE THREAD

**Issue by kpxupc** [shadowsocks/shadowsocks-org#91]
You can see the full paper here: http://www.cs.ucr.edu/~krish/imc17.pdf.  You can see the slides here: https://conferences.sigcomm.org/imc/2017/slides/IMC17.pdf
This is their project and project code: https://github.com/seclab-ucr/INTANG

Please read and let's start a constructive discussion to push things forward even more. 

Wang et al.根据对GFW状态机的新分析提出了新的TCP层穿墙方法，经过广泛测试成功率高达98%

**Comment by klzgrad** [comment]
It would be a separate project complementary to SS in the best case. TCP hacking requires root and much more engineering effort to reach the same level of usability as SS. I don't know if it is even possible to implement on Android or iOS.

**Comment by tony1016** [comment]
粗看了一下，讨论的都是HTTP等裸数据下TCP被RESET的解决方法，完全不适用已经使用Shadowsocks但是被检测出来的场景

**Comment by Mygod** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1437#issuecomment-341780402
