### ISSUE TITLE
Issues on shadowsocks-go repo need to be treated!

### ISSUE THREAD

**Issue by arthurkiller** [shadowsocks/shadowsocks-org#92]
Many developer has come up with problems while trying to use or contribute( just like me) to [this repo](https://github.com/shadowsocks/shadowsocks-go/issues).

This repo is leaking of management, and the issues should be treated.

So if you guys known someone or have some ways or just wanna someone to take over this problem, go and contact me, I'm willing to help

**Comment by arthurkiller** [comment]
@madeye

**Comment by arthurkiller** [comment]
I just wonder if there got any organizations or something just like Special-Interesting-Group to guiding who and how to contribute with shadowsocks community

**Comment by CNMan** [comment]
golang port repo owner and main contributor is @cyfdecyf ,we need wait for him to deal with that when he have free time.

**Comment by arthurkiller** [comment]
I have mailed him but nothing replayed @CNMan. If you guys get some special way, just tell him the situation about this repo and someone is willing to take a hand.

THX dude

**Comment by madeye** [comment]
I suggest you fork shadowsocks-go and maintain it as a new project. If you like, I can let you move that new project into the organization.

**Comment by arthurkiller** [comment]
@madeye Thx for reply, here is still some problem needs to clearify

1. If you mean to set up a totally new repo, riobard has do the same thing.

2. The problem is still many people using the shadowsocks-go ( maybe the repo name get a miss-leading, people just search for ss-go and did not find out that the ss-go is leaking management), 

They needs support and help.  

3. I guess we should not remove this repo( is this possible to remove a repo? perhaps rename is better).  All we need is just open up the permission on ss-go to make this repo get back on track.

**Comment by Mygod** [comment]
A fork means you add changes to the existing codebase at a different repo. If your fork is good, @madeye can put a deprecation sign at the original repo and put a link to your repo there.

**Comment by arthurkiller** [comment]
@Mygod I have do [this](https://github.com/arthurkiller/shadowsocks-go/)already and make up an [PR](https://github.com/shadowsocks/shadowsocks-go/pull/221) for about 5 mouths.

If this is ready to be added into?

**Comment by arthurkiller** [comment]
I think a branch for me to develop on is better

**Comment by madeye** [comment]
@arthurkiller Let's add all the AEAD ciphers first and rename your repo to `shadowsocks-go-v2` or similar. Then we can invite you transfer the project to shadowsocks org.

**Comment by arthurkiller** [comment]
AEAD has already done in my fork @madeye , and some developer has give some review on my PR already [PR link](https://github.com/shadowsocks/shadowsocks-go/pull/221)

**Comment by arthurkiller** [comment]
Hey dude, have you make any progress on this issue?
I comes up a solution here: add a developer branch for me to merge and contribute, and people can choose there choices

**Comment by madeye** [comment]
Please follow https://github.com/shadowsocks/shadowsocks-org/issues/92#issuecomment-342734887 if you want to maintain your project under shadowsocks-org.

**Comment by arthurkiller** [comment]
@madeye  Sorry , but what does it mean?

Is you guys possible to make up a branch for me to work on?

**Comment by madeye** [comment]
It means you need to rename your project and maintain it as a fork.

**Comment by arthurkiller** [comment]
Only this way? how about the shadowsocks-go? will it  be abandoned?

**Comment by madeye** [comment]
Nope, only deprecated.

It's because many third-party software depends on shadowsocks-go.

**Comment by arthurkiller** [comment]
problem solved, thx all of you
