### ISSUE TITLE
Please add explicit license text

### ISSUE THREAD

**Issue by jvalleroy** [shadowsocks/shadowsocks-org#93]
I see a mention of MIT license in this file:
https://github.com/shadowsocks/shadowsocks-org/blob/gh-pages/package.json#L32

But I think it's better to include the full license text. For example, https://choosealicense.com/licenses/mit/ suggests to "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders."

**Comment by celeron533** [comment]
File you mentioned is the license from a "third party" component (in this scenario, it is a test runner for Javascript because this repo has web developments) not the project itself.

**Comment by jvalleroy** [comment]
@celeron533 Ok, then I should ask: Does this repository have a license?

**Comment by celeron533** [comment]
Nop. :unicorn:

**Comment by jvalleroy** [comment]
Would it be possible to add a license?

The reason I'm asking, is that I'm working on integrating Shadowsocks into FreedomBox (https://freedombox.org/). So I would like to re-use the favicon logo (https://github.com/shadowsocks/shadowsocks-org/blob/gh-pages/assets/img/favicon/shadow.png). This would be used on the front page of the web interface, which shows all the services running on the box.

**Comment by jvalleroy** [comment]
Alternatively, I could use: https://commons.wikimedia.org/wiki/File:Shadowsocks_logo.png
which says it is Apache 2.0 licensed.

**Comment by madeye** [comment]
Sorry for the confusion here.

This site itself is licensed under MIT. https://github.com/shadowsocks/shadowsocks-org/blob/gh-pages/LICENSE
