### ISSUE TITLE
Auto balance?

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-org#96]
> TLDR: Please make all Shadowsocks client support multi-server connection 
> (One client can automatically connect to multiple servers without having user to manually switching)

Actually, inspired by this totally unrelated news:
Source: http://www.thepaper.cn/newsDetail_forward_1883858

Consider current mode: One or multiple clients sending and receiving (what appears to be) random data to a single server that usually listening a single IPv4 address. It's a dead giveaway of something tricky going on there. 

After saw that news, I realized that when IPv6 become available, we can then use a whole range of addresses to communicate with server (With appears to be different servers to the network), thus, make the firewall trying harder to do it's statistical job.

I know it's not very wise to make Shadowsocks client support range IP connection (i.e. Provide a range, connect one of the address in space randomly), however, it's much logical to support multi-server connection (or auto balance), so user can make their own pool of servers (or IPs) to connect when they need.

What you guys think?

**Comment by Mygod** [comment]
Fyi you can assign multiple IPv4 addresses to the same interface with virtual interface in Linux. Afaic this is not very useful.
