### ISSUE TITLE
Theory: A method that MAY prevent application level proxy detection on android device?

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-org#97]
> TLDR: Set up a relay between user and server and connect the relay instead. The application will never knew the address of that relay you connected.

Based on my limited knowledge on Android development, I found it's not very easy to figure out which Shadowsocks server I'm connected with at application level (non-rooted).

So in order for malicious application to detect the address of Shadowsocks server, it needs to send one or more queries to fetch current user's public IP address, and compare them to test whether or not those IP addresses is assigned to the mainland.

During this procedure, if one of those query go though a Shadowsocks server, then the IP address of that server can be reveled, then analyzed, and eventually blocked. 

If you setup a relay in between you and Shadowsocks server though, the situation may be changed, because the reveled IP address was not the IP address you actually used to connect to the server (You go through a relay).

So even the server IP gets blocked, you will not be affected because IP of the relay is still unknown to the application.

Hope somebody can test this theory see if it actually works.

**Comment by Mygod** [comment]
> So in order for malicious application to detect the address of Shadowsocks server, it needs to send one or more queries to fetch current user's public IP address, and compare them to test whether or not those IP addresses is assigned to the mainland.

So you're basically blocking all your oversea users. If you're paranoid about this situation, you can use apps VPN mode feature in shadowsocks-android and bypass every app by default.
